// ── Foreign-buyer SEO landing data ────────────────────────────────────────
// Powers /buying-property-in-dubai-as-[country]-citizen programmatic pages.
// Each market gets bespoke content covering local financing, tax, repatriation,
// and visa nuances — generic copy would not rank against actual local advisors.

export interface ForeignBuyerProfile {
  slug: string;
  country: string;        // "UK" / "Russian" / "Chinese" — appears in copy
  citizen: string;        // "British" / "Russian" / "Chinese" — for natural sentences
  flag: string;
  intro: string;
  whyDubai: string;
  legalStatus: string;
  financing: string;
  taxImplications: string;
  repatriation: string;
  preferredAreas: string[];
}

export const FOREIGN_BUYERS: ForeignBuyerProfile[] = [
  {
    slug: "uk-citizen",
    country: "UK",
    citizen: "British",
    flag: "🇬🇧",
    intro: "Dubai has been the single most active destination for British property capital outside the UK for the past five years. The combination of zero personal income tax, no capital gains tax, and a stable currency pegged to the US dollar has attracted both relocating professionals and remote investors.",
    whyDubai: "British buyers are typically drawn by three factors: tax efficiency relative to UK stamp duty and capital gains, the freehold ownership structure available in designated zones, and the practical convenience of a 7-hour direct flight from London. Many also use Dubai as a base for the Middle East, Africa, and South Asia. Rental yields of 5–8% gross materially exceed the typical 3–4% achievable in central London buy-to-let.",
    legalStatus: "UK citizens can buy freehold property in Dubai's designated freehold zones with no restrictions, no minimum investment requirement (beyond Golden Visa thresholds if pursuing residency), and full title-deed ownership. There is no requirement to be a UAE resident or to spend any time in the UAE. Properties can be held personally, through a UK limited company, or through a UAE free-zone entity (DIFC, ADGM).",
    financing: "UK income and credit history are acceptable to most UAE banks for non-resident lending. HSBC and Standard Chartered are particularly active in the UK expat segment with dedicated international mortgage products. Typical terms: 50% LTV, 4.5–6.5% interest, 25-year term. Pre-approval typically takes 14–21 working days. Some UK buyers leverage their UK property to release equity at lower UK rates and purchase cash in Dubai — often more efficient than a Dubai mortgage.",
    taxImplications: "UK residents remain liable for UK tax on worldwide rental income at marginal rates (up to 45%) plus 20% capital gains tax on disposal. UK non-residents (i.e., those who have left the UK and broken UK tax residency) pay UK tax only on UK-source income — Dubai rental and gains become tax-free. Many UK buyers structure their move to claim non-resident status before triggering significant gains. Inheritance tax is complex: UK-domiciled individuals are taxed on worldwide assets, including Dubai property, at 40% above the nil-rate band. Domicile-of-choice claims to break this require careful planning.",
    repatriation: "No UAE foreign-exchange controls. Funds can be wired to UK accounts in any amount at any time. UK banks may flag large inbound transfers under anti-money-laundering rules — keep records of property sale documents, mortgage statements, and original source-of-funds documentation. Most British buyers find HSBC Premier or Lloyds International accounts useful for AED ↔ GBP transfers.",
    preferredAreas: ["Dubai Marina", "Downtown Dubai", "Dubai Hills Estate", "Palm Jumeirah"],
  },
  {
    slug: "russian-citizen",
    country: "Russian",
    citizen: "Russian",
    flag: "🇷🇺",
    intro: "Russian capital has been one of the largest single contributors to Dubai property transaction volume since 2022. The combination of UAE neutrality, easy residency through property, and minimal documentation friction has made Dubai the destination of choice for Russian capital relocation.",
    whyDubai: "Russian buyers prioritise three things: capital preservation outside the Russian Federation, residency that doesn't require renouncing Russian citizenship, and assets that can be held in a stable currency. Dubai delivers all three. The AED is pegged to USD, providing a hedge against rouble volatility. The Golden Visa at AED 2M provides 10-year residency without giving up Russian citizenship. And Dubai's transaction infrastructure handles Russian capital efficiently — major brokers, lawyers, and developers have dedicated Russian-speaking teams.",
    legalStatus: "Russian citizens enjoy full freehold ownership rights in Dubai's designated zones. No restrictions on amount, type, or number of properties. Sanctions screening applies — major banks and developers conduct standard due diligence — but ordinary Russian buyers without sanctions exposure transact without issue. Properties can be held personally or through corporate structures (DIFC, RAK ICC, or offshore vehicles). Many Russian buyers use a UAE corporate vehicle for liability and inheritance reasons.",
    financing: "Mortgages for Russian non-residents are available but restricted. Sanctions complications mean fewer banks actively lend; Mashreq, Emirates NBD, and some private banks remain accessible. Cash purchase is overwhelmingly the route used — the majority of Russian buyers transact cash. For those seeking mortgage finance, expect 30–40% LTV, 5.5–7% rates, and documentation requirements significantly stricter than for European nationalities. Source-of-funds documentation is essential.",
    taxImplications: "Russia taxes residents on worldwide income at 13–15%. Russian tax residents (183+ days in Russia per year) remain liable to declare Dubai rental income and gains. Russians who relocate to UAE and become UAE tax residents (residence visa + UAE primary home + physical presence) generally escape Russian taxation on Dubai-source income, though this requires care given Russian tax law's residence tests. There is no UAE income tax, no capital gains tax, no inheritance tax on Dubai property.",
    repatriation: "Dubai imposes no exchange controls. Wires to Russian accounts have become operationally complex due to SWIFT restrictions affecting Russian banks; many Russian buyers route through correspondent banks in friendly jurisdictions (UAE, Türkiye, UAE branches of Russian banks like VTB or RSHB). Crypto-settled property transactions have become more common — Dubai's regulated crypto exchanges (Binance, Kraken, OKX, BitOasis) facilitate AED purchases against USDT and BTC, providing a route Russian buyers commonly use.",
    preferredAreas: ["Palm Jumeirah", "Dubai Marina", "JBR", "Business Bay"],
  },
  {
    slug: "chinese-citizen",

    country: "Chinese",
    citizen: "Chinese",
    flag: "🇨🇳",
    intro: "Chinese investment in Dubai property has scaled rapidly post-pandemic, with Chinese buyers now consistently among the top 3 transaction-volume nationalities. The appeal combines lifestyle diversification, Belt-and-Road business positioning, and the increasing complexity of capital deployment in mainland China.",
    whyDubai: "Chinese buyers cite three primary motivations: portfolio diversification outside CNY assets, easy international travel from a UAE base, and educational opportunities (top international schools in Dubai serving Chinese families). The Golden Visa provides 10-year residency that does not require giving up Chinese citizenship (China does not recognise dual citizenship but permits Chinese citizens to hold foreign residency). The 7-hour direct flight to most major Chinese cities and the AED-USD peg complete the picture.",
    legalStatus: "Chinese citizens can buy freehold property in Dubai's designated zones with no restrictions on volume or value. No minimum investment beyond Golden Visa thresholds. Properties can be held personally, through Hong Kong companies, or through UAE corporate vehicles. Many Chinese buyers use BVI or Hong Kong holding structures to optimise inheritance planning under both Chinese succession law and UAE inheritance rules.",
    financing: "Chinese-source income is accepted by most UAE banks, but the documentation requirements are stringent — Chinese tax returns, business bank statements, and source-of-funds verification with attestation. ICBC Dubai and Bank of China Dubai branches actively serve Chinese buyers with dedicated Mandarin-speaking teams. Typical terms: 40–50% LTV, 5–6.5% rates. Cash purchase remains the dominant route given the friction of cross-border financing.",
    taxImplications: "China taxes residents on worldwide income at progressive rates up to 45%. Chinese tax residents are technically required to declare Dubai rental income and any disposal gains. Enforcement varies. Many Chinese investors structure ownership through Hong Kong or BVI entities to manage this exposure. There is no UAE tax on rental income, capital gains, or inheritance for the property itself. Chinese state tax on disposal proceeds repatriated to mainland accounts can be triggered depending on the source of those proceeds.",
    repatriation: "China's $50,000 annual personal foreign-exchange limit creates the practical bottleneck for Chinese buyers. Methods used: aggregating across multiple family members' annual quotas, using corporate vehicles in Hong Kong (no FX cap), or settling property purchases through pre-existing offshore funds. Cash from sale proceeds in Dubai can be wired anywhere without UAE restriction — the constraint is on the receiving side in China. Many Chinese buyers prefer to leave rental income reinvested in Dubai (additional property purchases) rather than repatriate.",
    preferredAreas: ["Downtown Dubai", "Business Bay", "Dubai Marina", "Dubai Hills Estate"],
  },
  {
    slug: "american-citizen",
    country: "American",
    citizen: "American",
    flag: "🇺🇸",
    intro: "American buyers represent one of the fastest-growing segments in Dubai real estate, driven by a high-earning professional class seeking tax-efficient international diversification. Dubai's zero-tax structure, USD-pegged currency, and world-class lifestyle amenities make it an increasingly serious alternative to traditional US property markets.",
    whyDubai: "American buyers are attracted by three primary factors: rental yields of 5–8% that dwarf US coastal markets (New York, San Francisco average 2–4%), a property market with no capital gains tax at the local level, and the AED's USD peg which eliminates currency risk entirely. US tech professionals, finance executives, and entrepreneurs increasingly use Dubai as a tax-efficient base for international income, particularly following the pandemic normalisation of remote work. The flight from the US East Coast is 12–13 hours; West Coast 17–18 hours, which has historically limited Dubai's appeal to Americans — this is changing as non-stop routes increase.",
    legalStatus: "US citizens enjoy full freehold ownership rights in Dubai's designated zones with no restrictions. The UAE imposes no foreign buyer restrictions. However, the US is one of very few countries that taxes citizens on worldwide income regardless of residence — this significantly affects the financial calculus. Americans cannot escape US tax by becoming UAE residents. That said, the Foreign Earned Income Exclusion (FEIE) and Foreign Tax Credit (FTC) mechanisms provide partial relief. Properties can be held personally or through US LLCs, which can simplify US tax reporting while maintaining freehold status.",
    financing: "US income documentation is well-accepted by UAE banks, but American buyers face unique friction from FATCA (Foreign Account Tax Compliance Act) compliance requirements that some UAE banks find burdensome. HSBC UAE, Citibank UAE, and major UAE banks with US correspondent relationships are the most accessible lenders. Typical terms: 40–50% LTV, 4.5–6.5% rates, 25-year term. Many American buyers choose to purchase cash or use US HELOC/equity against existing US property (at lower US rates) to fund Dubai purchases.",
    taxImplications: "The US taxes citizens on worldwide income regardless of residence. Dubai rental income must be reported on Form 1040 as foreign-source income. Disposal gains are subject to US capital gains tax (20% long-term federal + state tax for residents). The FEIE (Foreign Earned Income Exclusion) does not apply to passive rental income. Americans can claim a Foreign Tax Credit but since Dubai has no income tax, there is no FTC to claim. FBAR (FinCEN 114) and FATCA Form 8938 filings are required if offshore financial accounts exceed $10,000/$50,000. Despite this, the zero UAE tax still provides a timing benefit — rental income is never double-taxed, and gains are only taxed on disposal.",
    repatriation: "No UAE FX controls. However, large transfers to US banks will trigger FBAR reporting obligations and possibly SAR (Suspicious Activity Report) reviews. Americans should maintain full documentation of property purchase, mortgage statements, and sale proceeds. US banks (Chase, Wells Fargo, Bank of America) routinely accept large international transfers from UAE with proper documentation. Citibank's global banking platform is particularly useful for AED ↔ USD transfers.",
    preferredAreas: ["Downtown Dubai", "Dubai Marina", "Palm Jumeirah", "DIFC"],
  },
  {
    slug: "canadian-citizen",
    country: "Canadian",
    citizen: "Canadian",
    flag: "🇨🇦",
    intro: "Canadian buyers have been a consistent top-10 nationality in Dubai property purchases for the past decade. High property prices in Toronto and Vancouver, combined with Canada's relatively high tax environment, have pushed affluent Canadians to seek tax-efficient diversification. Dubai offers a USD-pegged, high-yield alternative with a large Canadian expat community already in place.",
    whyDubai: "Canadian buyers primarily cite tax efficiency: rental yields of 5–8% in Dubai versus 3–4% in Toronto or 2–3% in Vancouver, with zero UAE tax compared to 50%+ Canadian marginal rates. Many Calgary-based oil and gas professionals have family or professional connections to the UAE, creating a natural pathway. Canada's foreign buyer bans (introduced 2023 in certain cities) have also pushed investment capital offshore. The 14-hour direct Air Canada Toronto–Dubai flight makes the market practical for regular visits.",
    legalStatus: "Canadian citizens have unrestricted freehold ownership rights in Dubai's designated zones. Canada does not tax non-residents on foreign property income (non-resident Canadians are taxed only on Canadian-source income), creating a significant incentive for Canadians who relocate or achieve non-resident status. For resident Canadians, worldwide income is taxable — but Dubai property is not subject to UAE tax, so there is no foreign tax credit available, meaning full Canadian tax applies on rental income.",
    financing: "Canadian income documentation is well-accepted by UAE banks. TD Bank, RBC, and BMO have international banking programs that facilitate UAE property purchases. UAE banks offering non-resident mortgages typically accept Canadian pay stubs, T4 slips, and NOA (Notice of Assessment) for underwriting. Standard terms: 40–50% LTV, 4.5–6.5% rates. Some Canadian buyers use HELOCs against their Canadian home equity (at lower Canadian rates) to fund Dubai cash purchases — particularly effective when Canadian rates are lower than UAE mortgage rates.",
    taxImplications: "Resident Canadians pay Canadian income tax (up to 53.53% combined federal-provincial) on worldwide rental income. Capital gains on foreign property are 50% included and taxed at marginal rates. Non-resident Canadians who have properly broken Canadian tax residency pay no Canadian tax on Dubai rental income or gains — this is a major incentive for Canadian expats in the UAE. Canada's departure tax (deemed disposition) applies to securities but generally not to real estate held directly. FINTRAC reporting applies to large inbound wire transfers.",
    repatriation: "No UAE exchange controls. Canada has no restrictions on receiving foreign funds, but large inbound wires (CAD 10,000+) trigger FINTRAC reports at the receiving institution. CDIC does not insure foreign-currency deposits. Most Canadian buyers use their main Canadian bank account for receiving rental remittances — BMO Harris and TD's international banking platforms handle AED ↔ CAD transfers efficiently.",
    preferredAreas: ["Dubai Marina", "Downtown Dubai", "JVC", "Dubai Hills Estate"],
  },
  {
    slug: "australian-citizen",
    country: "Australian",
    citizen: "Australian",
    flag: "🇦🇺",
    intro: "Australia has one of the largest expat communities in Dubai, and Australian buyers have been active in the market for over 20 years. The combination of familiar common-law legal structures, English-language transactions, and yields that handily exceed Sydney and Melbourne equivalents has created a loyal buyer base.",
    whyDubai: "Australian buyers are motivated by the stark yield differential: Dubai offers 5–8% gross yields versus 2–3% in Sydney and Melbourne. Australia's property market is chronically undersupplied and overvalued by income multiples — many Australians find better value and higher income returns in Dubai with a smaller capital outlay. The time zone (AEDT is GMT+11, Dubai is GMT+4, making a 7-hour difference) is manageable for remote ownership. FIRB (Foreign Investment Review Board) restrictions apply to Australian domestic property but do not apply to UAE purchases.",
    legalStatus: "Australian citizens have full freehold ownership rights in Dubai's designated zones. FIRB restrictions that apply to foreign purchases of Australian property do not apply to non-Australian property — Australian citizens are free to buy in Dubai without any FIRB approval. Properties can be held personally, through Australian trusts, or through UAE corporate structures. Many Australian buyers in the HNWI segment use discretionary family trusts or SMSFs (Self-Managed Super Funds) to hold Dubai property — though SMSF ownership involves specific ATO compliance considerations.",
    financing: "Australian income documentation (payslips, tax returns, PAYG summaries) is well-accepted by UAE banks. Commonwealth Bank, ANZ, and NAB have international banking arms, and their income documentation is familiar to UAE underwriters. HSBC Australia's international mortgage product provides a direct channel. Typical non-resident terms: 40–50% LTV, 4.5–6.5%. Some Australians use Australian equity release or investment loans to purchase cash in Dubai — Australian variable rates have historically been competitive versus UAE fixed rates.",
    taxImplications: "Australia taxes residents on worldwide income. Dubai rental income is assessable for Australian tax purposes at marginal rates (up to 47% including Medicare Levy). Capital gains on foreign property are included at 50% discount (for assets held over 12 months) and taxed at marginal rates. Australian non-residents (those who have broken Australian tax residency by living abroad long-term) pay no Australian tax on Dubai rental income. The ATO has specific guidance on SMSF foreign property investments — rental income and gains flow through and are taxed at 15% during accumulation phase.",
    repatriation: "No UAE exchange controls. AUSTRAC (Australia's financial intelligence agency) monitors large inbound transfers under AML laws but imposes no capital controls. Most Australian banks accept AED-sourced transfers with proper documentation. AUD is freely convertible — the AED ↔ AUD cross is liquid and spreads are tight through major banks.",
    preferredAreas: ["Dubai Marina", "JBR", "Palm Jumeirah", "The Springs"],
  },
  {
    slug: "german-citizen",
    country: "German",
    citizen: "German",
    flag: "🇩🇪",
    intro: "Germany has a large and established expat community in Dubai, and German buyers have been investing in Dubai property for over 15 years. High German income tax rates, low German property yields, and a well-travelled professional class have created sustained demand. The UAE-Germany tax treaty provides additional structuring clarity.",
    whyDubai: "German buyers are primarily motivated by yield and tax planning. Germany offers residential rental yields of 2–4% (net below 2% after taxes), while Dubai offers 5–8% gross with zero local taxation. Germany's top income tax rate of 45% (plus solidarity surcharge and church tax) means that Dubai rental income is significantly more valuable on an after-tax basis than German equivalents — for those who are not German tax residents. The flight from Frankfurt is 6 hours, making Dubai one of the most practically accessible international markets for German investors.",
    legalStatus: "German citizens have unrestricted freehold ownership rights in Dubai's designated zones. Germany and the UAE have a Double Taxation Agreement (DTA) — the 2013 UAE-Germany DTA provides that UAE property income and gains are taxed only in the UAE (where the rate is zero), not in Germany — but only for German non-residents or under specific treaty conditions. German residents still pay German tax on worldwide income under Unbeschränkte Steuerpflicht (unlimited tax liability), but the DTA often provides a credit or exemption. Structuring through a UAE free zone entity (DIFC or Abu Dhabi Global Market) can provide additional clarity.",
    financing: "German income documentation (Gehaltsabrechnungen, Steuerbescheid) is accepted by UAE bank underwriters. Deutsche Bank has Dubai representation. Commerzbank's international banking handles EUR ↔ AED transfers. UAE non-resident mortgage terms: 40–50% LTV, 4.5–6.5% rates. German buyers often use German Bausparverträge (building savings contracts) equity or low-rate German investment loans to fund Dubai cash purchases, given that German mortgage rates are often lower than UAE non-resident rates.",
    taxImplications: "Germany taxes residents (Unbeschränkte Steuerpflicht) on worldwide income. Dubai rental income must be declared on the German Einkommensteuererklärung. The UAE-Germany DTA (Article 6) provides that income from immovable property is taxable in the country where the property is situated — UAE — which taxes at 0%. Germany applies the Progressionsvorbehalt (progression clause), meaning Dubai income is tax-exempt in Germany but is considered when computing the German tax rate on remaining German income. Capital gains on property held over 10 years are also tax-free in Germany under §23 EStG.",
    repatriation: "No UAE exchange controls. Germany has no capital controls, but BaFin (German financial regulator) and AML rules mean large inbound transfers from the UAE require documentation. EUR ↔ AED transfers are efficient through Deutsche Bank, Commerzbank, and Wise Business. SEPA transfers are not directly applicable for AED, but SWIFT EUR transfers to German IBANs are straightforward.",
    preferredAreas: ["Downtown Dubai", "Business Bay", "Dubai Hills Estate", "The Greens"],
  },
  {
    slug: "french-citizen",
    country: "French",
    citizen: "French",
    flag: "🇫🇷",
    intro: "France has a substantial professional expat community in Dubai, and French buyers have been consistently active in Dubai property since the early 2000s. High French tax rates, the IFI (Impôt sur la Fortune Immobilière — wealth tax on real estate), and Dubai's lifestyle offering for French-speaking families have created strong and sustained demand.",
    whyDubai: "French buyers are primarily driven by tax efficiency: France's top marginal income tax rate is 45% plus social charges (up to 17.2% for investment income) giving an effective rate exceeding 60% on passive investment income. France also applies the IFI — a wealth tax of 0.5–1.5% annually on net real estate assets above €1.3M worldwide. Moving to Dubai eliminates both: zero UAE income tax, zero UAE wealth tax. French citizens can become UAE tax residents by obtaining a UAE residency visa (property investment of AED 2M+ qualifies) and spending 183+ days per year in UAE, effectively exiting the French tax net.",
    legalStatus: "French citizens enjoy full freehold ownership rights in Dubai's designated zones. France and the UAE have a DTA (Convention fiscale franco-émiratie) — signed in 1989 — which provides that property income from immovable assets is taxed in the country of location (UAE, 0%). French tax residents remain subject to French tax under the worldwide income principle, but can claim treaty relief. French non-residents are taxed only on French-source income. French property located in Dubai is not subject to the IFI for non-residents.",
    financing: "French income documentation (bulletins de paie, avis d'imposition) is accepted by UAE banks. BNP Paribas, Société Générale, and Crédit Agricole have UAE or Middle East presences. UAE non-resident mortgage terms: 40–50% LTV, 4.5–6.5% rates. French buyers often leverage low-rate Prêt Immobilier in France against existing French property to fund Dubai cash purchases.",
    taxImplications: "French residents (résidents fiscaux) pay income tax on worldwide income including Dubai rental. Social charges (prélèvements sociaux) at 17.2% apply on investment income. The IFI applies to real estate assets worldwide for French residents above €1.3M net. Capital gains on foreign property are taxed at a flat 19% plus 17.2% social charges (or progressive rate if higher) for French residents. Non-residents pay only on French-source income — Dubai rental and gains are entirely exempt from French tax for non-residents. The UAE-France DTA provides significant planning opportunities for those who achieve non-resident status.",
    repatriation: "No UAE exchange controls. France has no capital controls, but Tracfin (French financial intelligence unit) monitors large inbound transfers. EUR ↔ AED transfers are efficient through BNP Paribas, Société Générale, and Wise. SEPA-compatible transfers from UAE AED accounts to French IBAN require a SWIFT/BIC route.",
    preferredAreas: ["Business Bay", "Dubai Marina", "JVC", "Downtown Dubai"],
  },
  {
    slug: "vietnamese-citizen",
    country: "Vietnamese",
    citizen: "Vietnamese",
    flag: "🇻🇳",
    intro: "Vietnam's rapidly growing high-net-worth class has discovered Dubai as a premier destination for overseas property investment. With Vietnam's own property regulations making foreign property accessible and government-controlled, Dubai's open freehold market with no foreign buyer restrictions is an attractive counterpoint. The Vietnamese community in Dubai has grown substantially since 2020.",
    whyDubai: "Vietnamese buyers are motivated by diversification beyond Vietnam's tightly regulated domestic market, where foreign investors face significant ownership restrictions and developers have encountered high-profile liquidity challenges. Dubai offers full freehold ownership with strong DLD registry protections, international bank mortgages, and rental yields of 5–8% — versus Vietnam's 3–5% gross yields in Ho Chi Minh City (with significantly higher management complexity). The AED-USD peg provides a stable reference currency relative to the VND. The UAE Golden Visa through property investment provides a stable visa pathway that many Vietnamese HNWIs value for international travel.",
    legalStatus: "Vietnamese citizens enjoy full freehold ownership rights in Dubai's designated zones. Vietnam does not restrict outbound property investment, though SBVN (State Bank of Vietnam) foreign exchange controls apply to transferring funds abroad. Dubai imposes no restrictions on Vietnamese nationals. Properties can be held personally or through corporate structures. Vietnamese buyers often use offshore vehicles (BVI, Singapore holding companies) to manage both FX controls and inheritance considerations.",
    financing: "UAE bank financing is available to Vietnamese nationals, though documentation complexity is higher than for European or North American buyers. Vietnamese tax returns (tờ khai thuế TNCN), employment contracts, and source-of-funds documentation in Vietnamese must typically be translated and apostilled. Some buyers use Singapore or Hong Kong bank facilities to bridge the financing gap. Cash purchase is the dominant route for Vietnamese buyers. Vietcombank and BIDV's international offices can facilitate AED fund movements.",
    taxImplications: "Vietnam taxes personal income at progressive rates up to 35% on employment income; foreign-source rental income and capital gains from overseas property are technically taxable in Vietnam under Circular 111. In practice, enforcement is limited for offshore property held by non-resident Vietnamese, but risk is increasing as OECD CRS (Common Reporting Standard) data exchange comes online. The UAE has signed the MCAA (Multilateral Competent Authority Agreement) — Vietnamese tax authorities will receive CRS data on Vietnamese nationals' UAE accounts and property from 2024 onward. Proper tax structuring is increasingly important.",
    repatriation: "Vietnam's SBV FX controls limit outbound transfers — individuals may remit up to $200,000 per year for overseas property purchases with SBV approval. Larger transfers require specific SBV documentation. Corporate vehicles in Singapore or Hong Kong (outside VND/SBV constraints) are commonly used. Inbound transfers from Dubai to Vietnamese VND accounts require SBV approval above certain thresholds. Many Vietnamese buyers leave rental income reinvested in Dubai rather than repatriate to Vietnam.",
    preferredAreas: ["Business Bay", "JVC", "Dubai Marina", "Arjan"],
  },
  {
    slug: "israeli-citizen",
    country: "Israeli",
    citizen: "Israeli",
    flag: "🇮🇱",
    intro: "Israeli buyers have transformed into one of Dubai's fastest-growing investor nationalities following the Abraham Accords normalisation of UAE-Israel relations in September 2020. Direct flights, business cooperation, and the subsequent opening of the Israeli market to the UAE have driven a surge in Israeli property investment. Tel Aviv property yields of just 2–3% make Dubai's 5–8% highly attractive.",
    whyDubai: "Israeli buyers are motivated by two primary factors: yield (Dubai's 5–8% versus Tel Aviv's 2–3%) and diversification from Israel's overheated domestic property market where average prices have increased 150%+ since 2010. The Abraham Accords have created direct business relationships, making Dubai a logical extension of Israeli business networks in the Gulf. El Al and other airlines now operate multiple direct TLV–DXB daily flights (3.5 hours). The UAE Golden Visa at AED 2M provides a convenient second residency option that many Israeli HNWIs value. An Israel-UAE tax treaty was signed in 2023, providing important clarity for structuring.",
    legalStatus: "Israeli citizens have full freehold ownership rights in Dubai's designated zones — this was specifically enabled by the Abraham Accords normalisation. Israel-UAE relations are normalised with full diplomatic representation. Properties can be held personally or through Israeli or UAE corporate vehicles. Many Israeli buyers use Israeli holding companies (חברה ישראלית) or UAE free zone companies to structure ownership for tax and estate-planning efficiency.",
    financing: "UAE banks have become comfortable with Israeli documentation following the Abraham Accords, and several major UAE banks now have dedicated Israeli client desks. Israeli pay stubs, Tofes 106 (annual tax summary), bank statements, and source-of-funds documentation are all accepted. Bank Hapoalim and Bank Leumi have Dubai-area correspondent relationships. UAE non-resident mortgage terms: 40–50% LTV, 4.5–6.5% rates. Israeli buyers also use Israeli bank Mashkantaot (mortgages) against Israeli property to fund Dubai cash purchases.",
    taxImplications: "Israel taxes residents on worldwide income. Dubai rental income is taxable in Israel at marginal rates (up to 47% for high earners). The Israel-UAE DTA (signed 2023, ratifying in progress as of 2026) provides that property income is taxed in the country where the property is located — UAE (0%). Capital gains from Israeli residents disposing of UAE property are taxed at 25% (for companies) or 25–30% (individuals) in Israel, with treaty relief expected once the DTA enters into full force. Israeli non-residents pay tax only on Israeli-source income — Dubai rental is entirely exempt. Many Israeli buyers time their UAE property disposals to non-resident periods.",
    repatriation: "Israel has no foreign-exchange controls — Israeli shekels are fully convertible. Bank of Israel does not restrict outbound property investment. Large inbound transfers (ILS or USD) to Israeli banks require standard AML documentation under Israeli Money Laundering Prohibition Law. Israeli banks (Leumi, Hapoalim, Discount, Mizrahi) all handle international wires efficiently. ILS ↔ AED transfers are straightforward via SWIFT with competitive rates through Israeli bank foreign-exchange desks.",
    preferredAreas: ["Downtown Dubai", "Business Bay", "Palm Jumeirah", "Dubai Marina"],
  },
];

export function findForeignBuyer(slug: string): ForeignBuyerProfile | undefined {
  return FOREIGN_BUYERS.find((b) => b.slug === slug);
}
