// Shared content for property-type SEO landing pages.
// Powers /apartments, /villas, /penthouses, /offices, /townhouses, /warehouses, /land-for-sale

export interface PropertyTypePage {
  slug: string;           // URL slug
  searchType: string;     // value passed to /search?type=
  searchIntent?: string;  // optional intent= param
  icon: string;
  en: PropertyTypeLocale;
  ru: PropertyTypeLocale;
  ar: PropertyTypeLocale;
  zh: PropertyTypeLocale;
}

export interface PropertyTypeLocale {
  metaTitle: string;
  metaDesc: string;       // max 155 chars
  h1: string;
  h1sub: string;
  heroDesc: string;
  stats: { n: string; label: string }[];
  highlights: { title: string; body: string }[];
  areas: string[];
  faqs: { question: string; answer: string }[];
  ctaSearch: string;
  keywords: string[];
}

export const PROPERTY_TYPE_PAGES: PropertyTypePage[] = [
  {
    slug: "apartments",
    searchType: "Apartment",
    icon: "🏢",
    en: {
      metaTitle: "Apartments for Sale & Rent in Dubai | Studios to 4BR | Binayah",
      metaDesc: "Browse Dubai apartments — studios, 1, 2, 3 & 4-bedroom units for sale and rent. Verified listings in Marina, Downtown, JVC, Business Bay. Binayah Properties.",
      h1: "Apartments in Dubai",
      h1sub: "Studios to 4-Bedroom | Sale & Rent",
      heroDesc: "Dubai's apartment market spans everything from AED 350K studios in JVC to AED 20M+ sky residences in Downtown. Browse 2,500+ verified listings with Binayah's AI-powered search.",
      stats: [{ n: "2,500+", label: "Apartments Listed" }, { n: "AED 350K", label: "Entry Price" }, { n: "5–8%", label: "Avg Rental Yield" }, { n: "60+", label: "Communities" }],
      highlights: [
        { title: "Studio & 1BR", body: "Entry-level Dubai apartments from AED 350K–700K. JVC, Dubai South, and Arjan offer the highest yields (6–9%) for rental investors." },
        { title: "2 & 3 Bedroom", body: "The most liquid segment. Families and expat couples drive demand in Marina, JLT, Business Bay, and Dubai Hills. Typical price: AED 900K–2.5M." },
        { title: "Luxury 3BR+", body: "Full-floor residences and penthouses in Downtown, Palm Jumeirah, and DIFC start from AED 3M and offer exceptional capital appreciation track records." },
      ],
      areas: ["Dubai Marina", "Downtown Dubai", "Jumeirah Village Circle", "Business Bay", "Dubai Hills Estate", "Jumeirah Lake Towers", "Palm Jumeirah", "Al Jaddaf"],
      faqs: [
        { question: "What is the average price of an apartment in Dubai?", answer: "Studio apartments start from AED 350,000–500,000 in suburban communities like JVC and Dubai South. 1-bedroom apartments range from AED 500K–1.2M. 2-bedroom units cost AED 900K–2.5M. Downtown and Palm Jumeirah 2-bedrooms start from AED 2.5M+. The citywide average price per sqft for apartments was approximately AED 1,450 in Q1 2026." },
        { question: "Where are the best areas to buy an apartment in Dubai?", answer: "For rental yield (6–9%): JVC, Dubai South, Al Jaddaf, Business Bay. For capital appreciation: Downtown Dubai, Palm Jumeirah, Dubai Marina. For families: Dubai Hills Estate, Arabian Ranches, Mirdif. For budget buyers: Dubai South, Arjan, International City." },
        { question: "Can foreigners buy apartments in Dubai?", answer: "Yes. All nationalities can purchase freehold apartments in Dubai's designated freehold zones — covering over 60 communities including Dubai Marina, Downtown, JVC, Business Bay, and Palm Jumeirah. No restrictions, no minimum investment (unless pursuing a Golden Visa), full title-deed ownership." },
        { question: "What are typical service charges for Dubai apartments?", answer: "Service charges in Dubai range from AED 8–25 per sqft per year depending on the building. A 1,000 sqft apartment in an average building costs AED 8,000–12,000 per year. Premium buildings (DIFC, Downtown, Palm) can exceed AED 20,000 per year. Service charges are paid by the owner, not the tenant." },
        { question: "Is it better to buy or rent an apartment in Dubai?", answer: "In most Dubai communities, buying is financially superior if you plan to stay 3+ years. The buy-vs-rent breakeven point at current prices and mortgage rates is typically 18–30 months. For shorter stays or maximum flexibility, renting makes more sense. The rent-to-price ratio in Dubai is typically 5–8%, making it one of the world's most attractive buy-to-let markets." },
      ],
      ctaSearch: "Browse All Apartments",
      keywords: ["apartments for sale dubai", "dubai apartments", "buy apartment dubai", "apartments for rent dubai", "studio apartment dubai"],
    },
    ru: {
      metaTitle: "Квартиры в Дубае | Студии и 1-4BR | Продажа и аренда | Binayah",
      metaDesc: "Квартиры в Дубае — студии, 1, 2, 3 и 4-комнатные апартаменты на продажу и в аренду. Проверенные объявления: Марина, Даунтаун, JVC, Бизнес-Бей.",
      h1: "Квартиры в Дубае",
      h1sub: "Студии и 1-4BR | Продажа и аренда",
      heroDesc: "Рынок апартаментов Дубая: от студий от 350 000 AED в JVC до резиденций за 20 млн AED в Даунтауне. Просматривайте более 2500 объектов с помощью поиска Binayah на базе ИИ.",
      stats: [{ n: "2 500+", label: "Квартир в базе" }, { n: "от 350 000 AED", label: "Цена входа" }, { n: "5–8%", label: "Средняя доходность" }, { n: "60+", label: "Районов" }],
      highlights: [
        { title: "Студия и 1BR", body: "Апартаменты начального уровня от 350 000–700 000 AED. JVC, Дубай Саут и Арджан — наивысшая доходность от аренды (6–9%)." },
        { title: "2 и 3 спальни", body: "Наиболее ликвидный сегмент. Семьи и экспаты выбирают Марина, JLT, Бизнес-Бей и Dubai Hills. Типичная цена: 900 000 – 2,5 млн AED." },
        { title: "Люкс 3BR+", body: "Квартиры целого этажа и пентхаусы в Даунтауне, Пальме Джумейра и DIFC — от 3 млн AED с отличным потенциалом роста стоимости." },
      ],
      areas: ["Дубай Марина", "Даунтаун Дубай", "Джумейра Вилладж Сёркл", "Бизнес-Бей", "Dubai Hills Estate", "Джумейра Лейк Тауэрс", "Пальма Джумейра", "Al Jaddaf"],
      faqs: [
        { question: "Какова средняя цена квартиры в Дубае?", answer: "Студии — от 350 000–500 000 AED в пригородных районах (JVC, Дубай Саут). Квартиры с 1 спальней — 500 000 – 1,2 млн AED. С 2 спальнями — 900 000 – 2,5 млн AED. В Даунтауне и на Пальме 2-комнатные — от 2,5 млн AED. Средняя цена за кв. фут в Q1 2026 — около 1 450 AED." },
        { question: "В каких районах лучше купить квартиру в Дубае?", answer: "По доходности от аренды (6–9%): JVC, Дубай Саут, Al Jaddaf, Бизнес-Бей. По росту стоимости: Даунтаун, Пальма Джумейра, Дубай Марина. Для семей: Dubai Hills Estate, Arabian Ranches. Бюджетный вариант: Дубай Саут, Арджан." },
        { question: "Могут ли граждане России купить квартиру в Дубае?", answer: "Да. Граждане России и других стран могут покупать фрихолд-квартиры в более чем 60 районах Дубая: Марина, Даунтаун, JVC, Бизнес-Бей, Пальма Джумейра. Ограничений нет, полный правоустанавливающий документ." },
        { question: "Каковы расходы на обслуживание квартиры в Дубае?", answer: "Сборы за обслуживание: 8–25 AED за кв. фут в год. Квартира площадью 100 кв. м в обычном здании — около 8 000–12 000 AED в год. Премиальные здания (DIFC, Даунтаун, Пальма) — более 20 000 AED в год. Оплачивает владелец, не арендатор." },
        { question: "Купить или арендовать квартиру в Дубае?", answer: "В большинстве районов покупка финансово выгоднее при планировании проживания от 3 лет. Точка безубыточности — обычно 18–30 месяцев. При соотношении аренды к цене 5–8% Дубай — один из лучших рынков buy-to-let в мире." },
      ],
      ctaSearch: "Смотреть все квартиры",
      keywords: ["квартиры дубай", "купить квартиру дубай", "аренда квартир дубай", "студия дубай", "апартаменты дубай"],
    },
    ar: {
      metaTitle: "شقق للبيع والإيجار في دبي | استوديو إلى 4 غرف | بناية",
      metaDesc: "تصفّح شقق دبي — استوديو، 1، 2، 3 و4 غرف للبيع والإيجار. إعلانات موثَّقة في المارينا ووسط المدينة وJVC والخليج التجاري.",
      h1: "شقق في دبي",
      h1sub: "استوديو إلى 4 غرف | بيع وإيجار",
      heroDesc: "يمتد سوق الشقق في دبي من استوديوهات بـ 350,000 درهم في JVC إلى مساكن سماوية تتجاوز 20 مليون درهم في وسط المدينة. تصفّح أكثر من 2,500 إعلان موثَّق.",
      stats: [{ n: "+2500", label: "شقة في القاعدة" }, { n: "350K درهم", label: "سعر البداية" }, { n: "5-8%", label: "متوسط العائد" }, { n: "+60", label: "مجتمعًا" }],
      highlights: [
        { title: "استوديو و1 غرفة", body: "شقق مستوى دخول من 350,000 إلى 700,000 درهم. JVC ودبي ساوث وأرجان — أعلى عوائد إيجارية (6-9%)." },
        { title: "2 و3 غرف", body: "الشريحة الأكثر سيولةً. تُقبل عليها العائلات والمغتربون في مارينا وJLT والخليج التجاري ودبي هيلز. السعر النموذجي: 900,000 - 2.5 مليون درهم." },
        { title: "فاخر 3BR+", body: "وحدات بطابق كامل وبنتهاوس في وسط المدينة والنخلة وDIFC — تبدأ من 3 ملايين درهم مع تقدير رأسمالي ممتاز." },
      ],
      areas: ["دبي مارينا", "وسط المدينة", "جميرا فيلدج سيركل", "الخليج التجاري", "دبي هيلز إستيت", "جميرا ليك تاورز", "نخلة جميرا", "الجداف"],
      faqs: [
        { question: "ما متوسط سعر الشقق في دبي؟", answer: "الاستوديوهات من 350,000 إلى 500,000 درهم في المجتمعات الضاحوية. غرفة واحدة: 500,000 إلى 1.2 مليون درهم. غرفتان: 900,000 إلى 2.5 مليون درهم. في وسط المدينة والنخلة تبدأ الغرفتان من 2.5 مليون درهم." },
        { question: "أين أفضل مناطق شراء الشقق في دبي؟", answer: "للعائد الإيجاري (6-9%): JVC، دبي ساوث، الجداف، الخليج التجاري. لارتفاع القيمة: وسط المدينة، النخلة، المارينا. للعائلات: دبي هيلز، أراضي الخيل. للميزانية المحدودة: دبي ساوث، أرجان." },
        { question: "هل يمكن للأجانب شراء شقق في دبي؟", answer: "نعم. يحق لجميع الجنسيات تملك شقق حرة في أكثر من 60 مجتمعًا بدبي، منها المارينا ووسط المدينة وJVC والخليج التجاري والنخلة، بموجب سند ملكية رسمي بلا قيود." },
        { question: "ما رسوم الخدمة لشقق دبي؟", answer: "رسوم الخدمة من 8 إلى 25 درهمًا للقدم المربعة سنويًا. شقة بـ 100 متر في مبنى متوسط: نحو 8,000-12,000 درهم سنويًا. المباني الفاخرة قد تتجاوز 20,000 درهم. يدفعها المالك لا المستأجر." },
        { question: "هل الشراء أم الإيجار أفضل في دبي؟", answer: "في معظم مجتمعات دبي، الشراء أجدى ماليًا عند التخطيط للإقامة 3 سنوات أو أكثر. نسبة الإيجار إلى السعر 5-8%، مما يجعل دبي من أفضل أسواق الاستثمار الإيجاري عالميًا." },
      ],
      ctaSearch: "تصفّح جميع الشقق",
      keywords: ["شقق للبيع دبي", "شقق للإيجار دبي", "شراء شقة دبي", "استوديو دبي"],
    },
    zh: {
      metaTitle: "迪拜公寓出售与出租 | 单间至4卧室 | Binayah Properties",
      metaDesc: "浏览迪拜公寓——单间、1、2、3和4卧室，可购买或出租。Marina、市中心、JVC、商业湾已核实房源。",
      h1: "迪拜公寓",
      h1sub: "单间至4卧室 | 出售与出租",
      heroDesc: "迪拜公寓市场从JVC的35万迪拉姆单间公寓到市中心2000万迪拉姆以上的顶层豪宅应有尽有。浏览Binayah AI驱动搜索中2500多套核实房源。",
      stats: [{ n: "2,500+", label: "在售公寓" }, { n: "35万AED", label: "入市价格" }, { n: "5-8%", label: "平均租金收益" }, { n: "60+", label: "社区" }],
      highlights: [
        { title: "单间及1卧室", body: "入门级迪拜公寓，价格35-70万迪拉姆。JVC、迪拜南区和Arjan提供最高租金收益（6-9%）。" },
        { title: "2及3卧室", body: "流动性最强的细分市场。家庭和外籍人士青睐Marina、JLT、商业湾和迪拜山。典型价格：90万-250万迪拉姆。" },
        { title: "豪华3卧室+", body: "市中心、棕榈岛和DIFC的整层住宅和顶层公寓起价300万迪拉姆，资本增值记录出色。" },
      ],
      areas: ["迪拜Marina", "市中心", "朱美拉村庄圈", "商业湾", "迪拜山庄", "朱美拉湖塔", "棕榈岛", "Jaddaf"],
      faqs: [
        { question: "迪拜公寓的平均价格是多少？", answer: "郊区社区（JVC、迪拜南区）单间公寓起价35-50万迪拉姆。1卧室50-120万迪拉姆。2卧室90-250万迪拉姆。市中心和棕榈岛2卧室起价250万迪拉姆以上。2026年Q1公寓均价约每平方英尺1,450迪拉姆。" },
        { question: "迪拜哪些地区最适合买公寓？", answer: "租金收益（6-9%）：JVC、迪拜南区、Jaddaf、商业湾。资本增值：市中心、棕榈岛、迪拜Marina。家庭适合：迪拜山庄、Arabian Ranches。预算有限：迪拜南区、Arjan。" },
        { question: "外国人可以在迪拜购买公寓吗？", answer: "可以。所有国籍均可在迪拜60多个自由持有区购买公寓，包括Marina、市中心、JVC、商业湾和棕榈岛。无限制，无最低投资额（申请黄金签证除外），完全产权。" },
        { question: "迪拜公寓的物业费是多少？", answer: "迪拜物业费每年每平方英尺8-25迪拉姆。100平米普通楼盘每年约8,000-12,000迪拉姆。豪华楼盘（DIFC、市中心、棕榈岛）可超过20,000迪拉姆/年。由业主而非租客支付。" },
        { question: "在迪拜买房还是租房更合算？", answer: "大多数迪拜社区，计划居住3年以上买房更合算。按揭租金盈亏平衡点通常为18-30个月。迪拜租售比5-8%，是全球最具吸引力的买入出租市场之一。" },
      ],
      ctaSearch: "浏览所有公寓",
      keywords: ["迪拜公寓出售", "迪拜公寓出租", "购买迪拜公寓", "迪拜单间公寓"],
    },
  },

  {
    slug: "villas",
    searchType: "Villa",
    icon: "🏡",
    en: {
      metaTitle: "Villas for Sale & Rent in Dubai | Luxury to Family | Binayah",
      metaDesc: "Browse Dubai villas — 3 to 7-bedroom standalone villas, semi-detached, and townhouses for sale and rent. Arabian Ranches, Palm, Dubai Hills. Binayah Properties.",
      h1: "Villas in Dubai",
      h1sub: "3–7 Bedrooms | Gated Communities",
      heroDesc: "Dubai's villa market ranges from AED 2M family homes in Arabian Ranches to AED 100M+ ultra-luxury estates on Palm Jumeirah and Emirates Hills. Find your perfect home with Binayah.",
      stats: [{ n: "800+", label: "Villas Listed" }, { n: "AED 2M", label: "Entry Price" }, { n: "4–6%", label: "Avg Rental Yield" }, { n: "25+", label: "Villa Communities" }],
      highlights: [
        { title: "Family Villas", body: "3–5 bedroom villas in gated communities like Arabian Ranches, Jumeirah Golf Estates, and DAMAC Hills start from AED 2M–5M. These communities offer schools, parks, and clubhouses." },
        { title: "Waterfront Villas", body: "Palm Jumeirah signature villas (AED 15M–80M+) and Dubai Creek Harbour framed properties offer direct sea/creek access. Dubai's most sought-after and illiquid asset class." },
        { title: "Golf & Leisure Villas", body: "Jumeirah Golf Estates, Trump International, and Jumeirah Golf Club communities offer villas with direct fairway or course views from AED 5M–20M." },
      ],
      areas: ["Arabian Ranches", "Palm Jumeirah", "Dubai Hills Estate", "Jumeirah Golf Estates", "DAMAC Hills", "Mudon", "Mirdif", "Al Barari"],
      faqs: [
        { question: "What is the average price of a villa in Dubai?", answer: "3-bedroom villas in established communities (Arabian Ranches, DAMAC Hills) start from AED 2M–3.5M. 4-5 bedroom villas range from AED 3.5M–8M. Waterfront villas (Palm Jumeirah, Jumeirah Bay) range from AED 15M–80M. Emirates Hills mega-villas can exceed AED 200M." },
        { question: "What are the best villa communities in Dubai?", answer: "Family living: Arabian Ranches (3 phases), Dubai Hills Estate, Mudon. Golf communities: Jumeirah Golf Estates, DAMAC Hills. Luxury/waterfront: Palm Jumeirah, Emirates Hills. Value: Town Square, Akoya Oxygen, The Springs." },
        { question: "Can foreigners buy villas in Dubai?", answer: "Yes. Foreigners can buy villas in Dubai's freehold zones, which include most villa communities. There are no restrictions by nationality. Some masterplan communities like Jumeirah and Al Wasl are leasehold (not freehold) — your Binayah agent will clarify before you purchase." },
        { question: "What are service charges for Dubai villas?", answer: "Villa service charges range from AED 2–8 per sqft of plot area per year, depending on the community. Arabian Ranches averages AED 3–5/sqft; DAMAC Hills AED 4–6/sqft. Service charges cover security, landscaping, pools, and community maintenance." },
        { question: "Is buying a villa in Dubai a good investment?", answer: "Dubai villa prices have appreciated 35–60% across prime communities since 2021, driven by post-pandemic lifestyle demand from European, Russian, and Chinese buyers. Rental yields of 4–6% are lower than apartments but villas attract longer-tenancy tenants (2–3 year leases), reducing vacancy risk. Villa supply is more constrained than apartment supply, supporting price floors." },
      ],
      ctaSearch: "Browse All Villas",
      keywords: ["villas for sale dubai", "villa dubai", "buy villa dubai", "villas for rent dubai", "luxury villa dubai"],
    },
    ru: {
      metaTitle: "Виллы в Дубае | Продажа и аренда | 3–7 спален | Binayah",
      metaDesc: "Виллы в Дубае — отдельностоящие и таунхаусы с 3-7 спальнями на продажу и в аренду. Arabian Ranches, Пальма, Dubai Hills. Binayah Properties.",
      h1: "Виллы в Дубае",
      h1sub: "3–7 спален | Охраняемые комьюнити",
      heroDesc: "Рынок вилл Дубая: от семейных домов за 2 млн AED в Arabian Ranches до ультра-люксовых поместий за 100 млн AED на Пальме. Найдите идеальный дом с Binayah.",
      stats: [{ n: "800+", label: "Вилл в базе" }, { n: "от 2 млн AED", label: "Цена входа" }, { n: "4–6%", label: "Средняя доходность" }, { n: "25+", label: "Комьюнити" }],
      highlights: [
        { title: "Семейные виллы", body: "Виллы с 3–5 спальнями в охраняемых комьюнити Arabian Ranches, Jumeirah Golf Estates, DAMAC Hills — от 2–5 млн AED. Школы, парки, клубы в шаговой доступности." },
        { title: "Виллы у воды", body: "Виллы на Пальме Джумейра (15–80+ млн AED) с прямым выходом к морю — наиболее ликвидный элитный актив Дубая." },
        { title: "Виллы у поля для гольфа", body: "Jumeirah Golf Estates, Trump International и другие клубные комьюнити — виллы с видом на поле от 5–20 млн AED." },
      ],
      areas: ["Arabian Ranches", "Пальма Джумейра", "Dubai Hills Estate", "Jumeirah Golf Estates", "DAMAC Hills", "Mudon", "Mirdif", "Al Barari"],
      faqs: [
        { question: "Какова средняя цена виллы в Дубае?", answer: "Виллы с 3 спальнями (Arabian Ranches, DAMAC Hills) — от 2–3,5 млн AED. С 4–5 спальнями — 3,5–8 млн AED. Виллы у воды (Пальма, Jumeirah Bay) — 15–80 млн AED. Мега-виллы Emirates Hills могут превышать 200 млн AED." },
        { question: "Лучшие комьюнити для вилл в Дубае?", answer: "Семейное проживание: Arabian Ranches, Dubai Hills Estate, Mudon. Гольф: Jumeirah Golf Estates, DAMAC Hills. Люкс/набережная: Пальма Джумейра, Emirates Hills. Бюджетный вариант: Town Square, The Springs." },
        { question: "Могут ли иностранцы купить виллу в Дубае?", answer: "Да. Иностранцы могут покупать виллы во фрихолд-зонах Дубая — большинство комьюнити относятся к ним. Ограничений по национальности нет. Ваш агент Binayah уточнит статус каждого конкретного комьюнити." },
        { question: "Каковы расходы на обслуживание виллы?", answer: "Сборы за обслуживание: 2–8 AED за кв. фут участка в год в зависимости от комьюнити. Arabian Ranches — 3–5 AED/кв. фут; DAMAC Hills — 4–6 AED/кв. фут." },
        { question: "Виллы в Дубае — хорошая инвестиция?", answer: "С 2021 года виллы в ключевых комьюнити выросли на 35–60%. Доходность от аренды 4–6% ниже, чем у апартаментов, но арендаторы вилл, как правило, заключают долгосрочные договоры (2–3 года), снижая риск простоя." },
      ],
      ctaSearch: "Смотреть все виллы",
      keywords: ["виллы дубай", "купить виллу дубай", "аренда виллы дубай", "вилла дубай цена"],
    },
    ar: {
      metaTitle: "فلل للبيع والإيجار في دبي | عائلية وفاخرة | بناية للعقارات",
      metaDesc: "تصفّح فلل دبي — 3 إلى 7 غرف، مستقلة وشبه مستقلة للبيع والإيجار. أراضي الخيل والنخلة ودبي هيلز.",
      h1: "فلل في دبي",
      h1sub: "3-7 غرف | مجتمعات مسوَّرة",
      heroDesc: "يتراوح سوق الفلل في دبي من منازل عائلية بـ 2 مليون درهم في أراضي الخيل إلى قصور فاخرة تتجاوز 100 مليون درهم على النخلة. اعثر على منزلك المثالي مع بناية.",
      stats: [{ n: "+800", label: "فيلا في القاعدة" }, { n: "2M درهم", label: "سعر البداية" }, { n: "4-6%", label: "متوسط العائد" }, { n: "+25", label: "مجتمعًا" }],
      highlights: [
        { title: "فلل عائلية", body: "فلل بـ 3-5 غرف في مجتمعات مسوَّرة: أراضي الخيل وJumeirah Golf Estates وDAMAC Hills — من 2-5 ملايين درهم. مدارس وحدائق وأندية في المتناول." },
        { title: "فلل بحرية", body: "فلل نخلة جميرا الأيقونية (15-80 مليون+ درهم) مع إطلالات بحرية مباشرة — أكثر الأصول طلبًا في دبي." },
        { title: "فلل الغولف", body: "Jumeirah Golf Estates وTrump International — فلل بإطلالة على الملعب من 5-20 مليون درهم." },
      ],
      areas: ["أراضي الخيل", "نخلة جميرا", "دبي هيلز إستيت", "جميرا جولف إستيتس", "داماك هيلز", "موادون", "مردف", "البراري"],
      faqs: [
        { question: "ما متوسط سعر الفلل في دبي؟", answer: "الفلل بـ 3 غرف في مجتمعات راسخة: 2-3.5 مليون درهم. بـ 4-5 غرف: 3.5-8 ملايين. الفلل البحرية (النخلة، جميرا باي): 15-80 مليون درهم." },
        { question: "أفضل مجتمعات الفلل في دبي؟", answer: "للعائلات: أراضي الخيل، دبي هيلز، موادون. للغولف: جميرا جولف إستيتس، داماك هيلز. للفخامة/الواجهة البحرية: النخلة، إيميريتس هيلز. للميزانية المعقولة: تاون سكوير، ذا سبرينغز." },
        { question: "هل يمكن للأجانب شراء فلل في دبي؟", answer: "نعم. يحق للأجانب شراء فلل في مناطق التملك الحر في دبي، التي تشمل معظم مجتمعات الفلل. لا قيود على الجنسية. سيُوضّح وكيل بناية وضع كل مجتمع قبل الشراء." },
        { question: "ما رسوم خدمة الفلل في دبي؟", answer: "رسوم الخدمة 2-8 درهم للقدم المربعة من مساحة الأرض سنويًا. أراضي الخيل: 3-5 درهم/قدم²؛ داماك هيلز: 4-6 درهم/قدم²." },
        { question: "هل الفلل في دبي استثمار جيد؟", answer: "ارتفعت أسعار الفلل في المجتمعات الرئيسية 35-60% منذ 2021. العوائد الإيجارية 4-6% مع عقود إيجار طويلة الأمد (2-3 سنوات) تقلّل مخاطر الشغور." },
      ],
      ctaSearch: "تصفّح جميع الفلل",
      keywords: ["فلل للبيع دبي", "فلل للإيجار دبي", "شراء فيلا دبي", "فيلا فاخرة دبي"],
    },
    zh: {
      metaTitle: "迪拜别墅出售与出租 | 3-7卧室 | Binayah Properties",
      metaDesc: "浏览迪拜别墅——独栋和半独栋，3至7卧室，可购买或出租。Arabian Ranches、棕榈岛、迪拜山庄。",
      h1: "迪拜别墅",
      h1sub: "3-7卧室 | 封闭式社区",
      heroDesc: "迪拜别墅市场从Arabian Ranches的200万迪拉姆家庭住宅到棕榈岛1亿迪拉姆以上的超豪华庄园一应俱全。",
      stats: [{ n: "800+", label: "在售别墅" }, { n: "200万AED", label: "入市价格" }, { n: "4-6%", label: "平均租金收益" }, { n: "25+", label: "别墅社区" }],
      highlights: [
        { title: "家庭别墅", body: "Arabian Ranches、Jumeirah Golf Estates等封闭社区3-5卧室别墅，起价200-500万迪拉姆，配套学校、公园和会所。" },
        { title: "滨水别墅", body: "棕榈岛标志性别墅（1500-8000万迪拉姆以上）直面大海，是迪拜最稀缺的顶级资产。" },
        { title: "高尔夫别墅", body: "Jumeirah Golf Estates、Trump International等高尔夫社区别墅，俯瞰球场，起价500-2000万迪拉姆。" },
      ],
      areas: ["Arabian Ranches", "棕榈岛", "迪拜山庄", "Jumeirah Golf Estates", "DAMAC Hills", "Mudon", "Mirdif", "Al Barari"],
      faqs: [
        { question: "迪拜别墅的平均价格是多少？", answer: "知名社区3卧室别墅（Arabian Ranches、DAMAC Hills）起价200-350万迪拉姆。4-5卧室350-800万迪拉姆。滨水别墅（棕榈岛、Jumeirah Bay）1500-8000万迪拉姆。Emirates Hills超豪华别墅可超2亿迪拉姆。" },
        { question: "迪拜最好的别墅社区是哪些？", answer: "家庭生活：Arabian Ranches、迪拜山庄、Mudon。高尔夫：Jumeirah Golf Estates、DAMAC Hills。豪华/滨水：棕榈岛、Emirates Hills。性价比：Town Square、The Springs。" },
        { question: "外国人可以在迪拜购买别墅吗？", answer: "可以。外国人可在迪拜自由持有区购买别墅，涵盖大多数别墅社区，无国籍限制，完全产权。" },
        { question: "迪拜别墅的物业费是多少？", answer: "别墅物业费每年每平方英尺地块面积2-8迪拉姆。Arabian Ranches约3-5迪拉姆/平方英尺；DAMAC Hills约4-6迪拉姆/平方英尺。" },
        { question: "迪拜别墅是好的投资吗？", answer: "自2021年以来，核心社区别墅价格上涨35-60%。租金收益4-6%，租客通常签订2-3年长期租约，降低空置风险。别墅供应比公寓更受约束，支撑价格底部。" },
      ],
      ctaSearch: "浏览所有别墅",
      keywords: ["迪拜别墅出售", "迪拜别墅出租", "购买迪拜别墅", "迪拜豪华别墅"],
    },
  },

  {
    slug: "penthouses",
    searchType: "Apartment",
    icon: "🌆",
    en: {
      metaTitle: "Penthouses for Sale in Dubai | Luxury Sky Homes | Binayah",
      metaDesc: "Exclusive penthouses in Dubai — Downtown, Marina, Palm Jumeirah. Full-floor residences, private pools, panoramic views. Binayah Properties luxury specialists.",
      h1: "Penthouses in Dubai",
      h1sub: "Full-Floor Luxury | Private Pools & Views",
      heroDesc: "Dubai penthouses represent the pinnacle of urban living — private infinity pools, panoramic skyline views, and unmatched privacy at elevation. Browse Binayah's exclusive penthouse portfolio.",
      stats: [{ n: "AED 3M", label: "Entry Price" }, { n: "4,000+", label: "Avg Sqft" }, { n: "AED 50M+", label: "Ultra-Luxury" }, { n: "DIFC, Marina, Downtown", label: "Top Locations" }],
      highlights: [
        { title: "Sky Penthouses", body: "Full-floor penthouse residences in Downtown Dubai and Dubai Marina (30–80th floors) with 360° panoramic views. AED 5M–25M. Private elevator access, smart home systems." },
        { title: "Private Pool Penthouses", body: "Rooftop penthouses with plunge or full-size infinity pools in Palm Jumeirah, Jumeirah Bay Island, and Downtown. AED 10M–50M+." },
        { title: "Branded Penthouses", body: "Four Seasons, Armani, Bulgari, and Address-branded penthouses command the highest premiums (AED 20M–200M) and hold value best in down markets." },
      ],
      areas: ["Downtown Dubai", "Dubai Marina", "Palm Jumeirah", "DIFC", "Jumeirah Bay Island", "Business Bay", "Bluewaters Island"],
      faqs: [
        { question: "What is the price range for penthouses in Dubai?", answer: "Dubai penthouse prices range from AED 3M for 3-bedroom upper-floor units in mid-tier buildings to AED 200M+ for branded full-floor sky palaces on Palm Jumeirah and in DIFC. The sweet spot for investment penthouses is AED 5M–20M in Downtown Dubai and Dubai Marina." },
        { question: "What makes a penthouse different from a regular apartment in Dubai?", answer: "Penthouses typically occupy the top 1–3 floors of a building with larger floor plates (4,000–15,000+ sqft), higher ceilings (3.5–6m), private rooftop terraces, dedicated private lifts, and panoramic views. Service charges are typically 2–3x higher than standard apartments." },
        { question: "Are Dubai penthouses a good investment?", answer: "Premium penthouses in branded or landmark buildings have outperformed the general Dubai property market since 2021 — price appreciation of 50–100% for the right assets. However, the market is thin (limited supply and buyers), making exits slow. Penthouses are primarily a store of wealth rather than yield investments." },
        { question: "Which buildings have the best penthouses in Dubai?", answer: "Address Sky View, Armani Hotel Residences, Four Seasons Private Residences, 1/JBR, Como Residences on Palm Jumeirah, and XXI Century's ultra-prime developments consistently command the highest prices and strongest resale demand." },
      ],
      ctaSearch: "Browse Penthouses",
      keywords: ["penthouses dubai", "penthouse for sale dubai", "luxury penthouse dubai", "dubai sky penthouse"],
    },
    ru: {
      metaTitle: "Пентхаусы в Дубае | Люксовые апартаменты | Binayah",
      metaDesc: "Эксклюзивные пентхаусы в Дубае — Даунтаун, Марина, Пальма. Полноэтажные резиденции, частные бассейны, панорамные виды.",
      h1: "Пентхаусы в Дубае",
      h1sub: "Полноэтажный люкс | Частные бассейны и виды",
      heroDesc: "Пентхаусы Дубая — вершина городской жизни: частные бесконечные бассейны, панорамный вид на горизонт города, полная приватность на высоте. Просматривайте эксклюзивное портфолио Binayah.",
      stats: [{ n: "от 3 млн AED", label: "Цена входа" }, { n: "4 000+", label: "Кв. фут в среднем" }, { n: "50+ млн AED", label: "Ультра-люкс" }, { n: "DIFC, Марина, Даунтаун", label: "Лучшие локации" }],
      highlights: [
        { title: "Небесные пентхаусы", body: "Полноэтажные резиденции в Даунтауне и Марине (30–80 этажи) с панорамными видами 360°. 5–25 млн AED. Личный лифт, умный дом." },
        { title: "Пентхаусы с бассейном", body: "Кровельные пентхаусы с бассейном на Пальме Джумейра, Jumeirah Bay Island и в Даунтауне. 10–50+ млн AED." },
        { title: "Брендовые пентхаусы", body: "Пентхаусы Four Seasons, Armani, Bulgari, Address — самые высокие ценовые показатели и наибольшая устойчивость к спадам рынка." },
      ],
      areas: ["Даунтаун Дубай", "Дубай Марина", "Пальма Джумейра", "DIFC", "Jumeirah Bay Island", "Бизнес-Бей", "Bluewaters Island"],
      faqs: [
        { question: "Каков ценовой диапазон пентхаусов в Дубае?", answer: "Пентхаусы в Дубае: от 3 млн AED (3-комнатный верхний этаж в среднеэтажном здании) до 200+ млн AED (брендовый полноэтажный дворец на Пальме или в DIFC). Инвестиционный диапазон: 5–20 млн AED в Даунтауне и Марине." },
        { question: "Чем пентхаус отличается от обычной квартиры?", answer: "Пентхаусы, как правило, занимают 1–3 верхних этажа с большей площадью (4 000–15 000+ кв. фут), высокими потолками (3,5–6 м), частными кровельными террасами и персональными лифтами." },
        { question: "Пентхаус в Дубае — хорошая инвестиция?", answer: "Премиальные пентхаусы в брендовых зданиях с 2021 года показали рост 50–100%. Однако рынок узкий — ликвидность ниже, чем у квартир. Пентхаусы прежде всего инструмент сохранения капитала." },
      ],
      ctaSearch: "Смотреть пентхаусы",
      keywords: ["пентхаус дубай", "купить пентхаус дубай", "люксовый пентхаус дубай"],
    },
    ar: {
      metaTitle: "بنتهاوس للبيع في دبي | مساكن فاخرة في الأعالي | بناية",
      metaDesc: "بنتهاوس حصرية في دبي — وسط المدينة والمارينا والنخلة. وحدات بطابق كامل، مسابح خاصة، إطلالات بانورامية.",
      h1: "بنتهاوس في دبي",
      h1sub: "فخامة بطابق كامل | مسابح خاصة وإطلالات",
      heroDesc: "تُمثّل البنتهاوس في دبي قمة المعيشة الحضرية — مسابح لانهائية خاصة وإطلالات بانورامية على الأفق وخصوصية لا مثيل لها على الارتفاع.",
      stats: [{ n: "3M درهم", label: "سعر البداية" }, { n: "+4000", label: "متوسط القدم المربعة" }, { n: "+50M درهم", label: "فائق الفخامة" }, { n: "DIFC والمارينا", label: "أبرز الموقع" }],
      highlights: [
        { title: "بنتهاوس السماء", body: "وحدات بطابق كامل في وسط المدينة والمارينا (الطوابق 30-80) بإطلالات 360°. 5-25 مليون درهم. مصعد خاص ومنزل ذكي." },
        { title: "بنتهاوس بمسبح خاص", body: "بنتهاوس على الأسطح مع مسابح لانهائية في النخلة وجميرا باي ووسط المدينة. 10-50 مليون+ درهم." },
        { title: "بنتهاوس ذات علامات تجارية", body: "بنتهاوس فور سيزونز وأرماني وبولغاري وأدريس تحقق أعلى العلاوات وأفضل الأداء في فترات تراجع السوق." },
      ],
      areas: ["وسط المدينة", "دبي مارينا", "نخلة جميرا", "DIFC", "جميرا باي", "الخليج التجاري", "بلووترز"],
      faqs: [
        { question: "ما نطاق أسعار البنتهاوس في دبي؟", answer: "من 3 ملايين درهم لوحدات الطوابق العليا في المباني المتوسطة إلى 200 مليون درهم+ للقصور الجوية الفاخرة على النخلة وفي DIFC. النطاق الاستثماري المثالي: 5-20 مليون درهم في وسط المدينة والمارينا." },
        { question: "ما الفرق بين البنتهاوس والشقة العادية؟", answer: "يشغل البنتهاوس عادةً 1-3 طوابق علوية بمساحة أكبر (4,000-15,000+ قدم)، أسقف أعلى، تراسات سطحية خاصة، ومصعد خاص." },
        { question: "هل البنتهاوس في دبي استثمار جيد؟", answer: "حقق البنتهاوس في المباني الفاخرة ارتفاعًا 50-100% منذ 2021. غير أن السوق محدودة — السيولة أدنى من الشقق العادية. البنتهاوس أداة حفظ ثروة بالدرجة الأولى." },
      ],
      ctaSearch: "تصفّح البنتهاوس",
      keywords: ["بنتهاوس للبيع دبي", "بنتهاوس فاخر دبي", "شراء بنتهاوس دبي"],
    },
    zh: {
      metaTitle: "迪拜顶层公寓出售 | 豪华天空豪宅 | Binayah Properties",
      metaDesc: "迪拜独家顶层公寓——市中心、Marina、棕榈岛。整层住宅、私人泳池、全景视野。",
      h1: "迪拜顶层公寓",
      h1sub: "整层豪华 | 私人泳池与全景",
      heroDesc: "迪拜顶层公寓代表城市生活的巅峰——私人无边泳池、全景天际线视野以及高空中无与伦比的私密性。",
      stats: [{ n: "300万AED", label: "入市价格" }, { n: "4,000+", label: "平均平方英尺" }, { n: "5000万AED+", label: "超豪华" }, { n: "DIFC, Marina, 市中心", label: "顶级位置" }],
      highlights: [
        { title: "天空顶层公寓", body: "市中心和Marina整层住宅（30-80楼）360度全景视野，500-2500万迪拉姆，私人电梯，智能家居。" },
        { title: "私人泳池顶层公寓", body: "棕榈岛、Jumeirah Bay Island和市中心屋顶顶层公寓，配无边泳池，1000-5000万迪拉姆以上。" },
        { title: "品牌顶层公寓", body: "四季、阿玛尼、宝格丽、Address品牌顶层公寓溢价最高，在市场下行期保值能力最强。" },
      ],
      areas: ["市中心", "迪拜Marina", "棕榈岛", "DIFC", "Jumeirah Bay Island", "商业湾", "蓝水岛"],
      faqs: [
        { question: "迪拜顶层公寓的价格范围是多少？", answer: "从普通楼盘高层3卧室单元的300万迪拉姆，到棕榈岛和DIFC品牌整层天空宫殿的2亿迪拉姆以上。投资型顶层公寓的理想范围是市中心和Marina的500-2000万迪拉姆。" },
        { question: "顶层公寓与普通公寓有什么区别？", answer: "顶层公寓通常占据楼顶1-3层，面积更大（4,000-15,000+平方英尺），层高更高（3.5-6米），有私人屋顶露台和专用电梯。" },
        { question: "迪拜顶层公寓是好的投资吗？", answer: "品牌楼盘顶层公寓自2021年以来升值50-100%。但市场较窄，流动性低于普通公寓。顶层公寓主要是财富储存工具。" },
      ],
      ctaSearch: "浏览顶层公寓",
      keywords: ["迪拜顶层公寓", "迪拜penthouse出售", "迪拜豪华顶层公寓"],
    },
  },

  {
    slug: "offices",
    searchType: "Commercial",
    icon: "🏢",
    en: {
      metaTitle: "Offices for Sale & Rent in Dubai | Commercial Property | Binayah",
      metaDesc: "Commercial offices in Dubai — DIFC, Business Bay, JLT, Downtown. Fitted and shell offices for sale and rent. Binayah commercial property specialists.",
      h1: "Offices in Dubai",
      h1sub: "Sale & Rent | DIFC to Business Bay",
      heroDesc: "Dubai's commercial office market offers Grade A fitted offices in DIFC from AED 200/sqft rent to shell-and-core opportunities for bespoke fit-outs. Browse Binayah's verified commercial listings.",
      stats: [{ n: "AED 80/sqft", label: "Entry Rent/Year" }, { n: "AED 1,500/sqft", label: "Sale Entry" }, { n: "6–9%", label: "Commercial Yield" }, { n: "DIFC, JLT, BBay", label: "Top Locations" }],
      highlights: [
        { title: "Fitted Offices", body: "Move-in ready Grade A offices with IT, partitioning, and AC. DIFC fitted offices: AED 160–280/sqft/year. Business Bay: AED 80–130/sqft/year." },
        { title: "Shell & Core", body: "Unfit shell offices for custom build-out. AED 1,500–3,000/sqft to purchase. Lower initial fit-out gives flexibility for growing businesses." },
        { title: "Free Zone Offices", body: "DIFC, DMCC, Jebel Ali Free Zone, and Dubai South offices qualify for 100% foreign ownership, zero corporate tax, and full profit repatriation." },
      ],
      areas: ["DIFC", "Business Bay", "Jumeirah Lake Towers", "Downtown Dubai", "Dubai Internet City", "Dubai Media City", "Deira"],
      faqs: [
        { question: "What are commercial office prices in Dubai?", answer: "Office rent in Dubai: DIFC Grade A AED 160–280/sqft/year; Business Bay AED 80–130/sqft/year; JLT AED 60–100/sqft/year. For purchase: DIFC offices AED 2,500–5,000/sqft; Business Bay AED 1,500–2,500/sqft." },
        { question: "What is the process for a company to rent an office in Dubai?", answer: "You need a UAE trade licence to legally rent an office. For mainland companies: DED licence + tenancy contract + Ejari registration. For free zone companies: the free zone authority issues the licence and is usually the landlord. DIFC has its own authority (DIFCA) and common law legal system." },
        { question: "Can foreigners own commercial office space in Dubai?", answer: "Yes. Foreigners can buy commercial office space freehold in designated zones. Free zone offices (DIFC, DMCC, JLT) allow 100% foreign ownership with no local partner required, plus zero corporate tax." },
        { question: "What are typical commercial lease terms in Dubai?", answer: "Commercial leases in Dubai are typically 1–3 years, paid by post-dated cheques (1–4 cheques per year). Notice periods are 90 days. DIFC operates under English common law with more sophisticated lease structures. Service charges are separate and typically AED 15–35/sqft/year." },
      ],
      ctaSearch: "Browse Offices",
      keywords: ["offices for sale dubai", "office rent dubai", "commercial property dubai", "difc office", "business bay office"],
    },
    ru: {
      metaTitle: "Офисы в Дубае | Продажа и аренда | Коммерческая недвижимость | Binayah",
      metaDesc: "Коммерческие офисы в Дубае — DIFC, Бизнес-Бей, JLT, Даунтаун. Готовые и оболочные офисы на продажу и в аренду.",
      h1: "Офисы в Дубае",
      h1sub: "Продажа и аренда | DIFC–Бизнес-Бей",
      heroDesc: "Коммерческий рынок офисов Дубая: готовые офисы класса А в DIFC от 200 AED/кв. фут аренды и пространства под самостоятельную отделку. Просматривайте проверенные коммерческие объекты Binayah.",
      stats: [{ n: "от 80 AED", label: "Аренда кв. фут/год" }, { n: "от 1 500 AED", label: "Цена продажи" }, { n: "6–9%", label: "Коммерческая доходность" }, { n: "DIFC, JLT, Бей", label: "Топ-локации" }],
      highlights: [
        { title: "Готовые офисы", body: "Готовые к въезду офисы класса А с IT-инфраструктурой, перегородками и кондиционированием. DIFC: 160–280 AED/кв. фут/год. Бизнес-Бей: 80–130 AED/кв. фут/год." },
        { title: "Оболочные офисы", body: "Офисы без отделки под самостоятельный ремонт. Цена покупки: 1 500–3 000 AED/кв. фут. Гибкость для растущих компаний." },
        { title: "Офисы во фри-зонах", body: "Офисы в DIFC, DMCC, Джебель Али и Дубай Саут: 100% иностранное владение, нулевой корпоративный налог, полная репатриация прибыли." },
      ],
      areas: ["DIFC", "Бизнес-Бей", "Джумейра Лейк Тауэрс", "Даунтаун Дубай", "Дубай Интернет Сити", "Дубай Медиа Сити", "Дейра"],
      faqs: [
        { question: "Каковы цены на коммерческие офисы в Дубае?", answer: "Аренда: DIFC класс А — 160–280 AED/кв. фут/год; Бизнес-Бей — 80–130; JLT — 60–100. Покупка: DIFC — 2 500–5 000 AED/кв. фут; Бизнес-Бей — 1 500–2 500." },
        { question: "Могут ли иностранцы владеть коммерческим офисом в Дубае?", answer: "Да. Иностранцы могут покупать офисы в собственность во фрихолд-зонах. Офисы во фри-зонах (DIFC, DMCC, JLT) — 100% иностранное владение без местного партнёра, нулевой корпоративный налог." },
        { question: "Каков типичный срок аренды коммерческого офиса в Дубае?", answer: "Обычно 1–3 года, оплата постдатированными чеками (1–4 чека в год). Срок уведомления — 90 дней. Плата за обслуживание — отдельно, обычно 15–35 AED/кв. фут/год." },
      ],
      ctaSearch: "Смотреть офисы",
      keywords: ["офисы дубай", "аренда офиса дубай", "коммерческая недвижимость дубай"],
    },
    ar: {
      metaTitle: "مكاتب للبيع والإيجار في دبي | عقارات تجارية | بناية",
      metaDesc: "مكاتب تجارية في دبي — DIFC والخليج التجاري وJLT ووسط المدينة. مكاتب جاهزة وقابلة للتجهيز للبيع والإيجار.",
      h1: "مكاتب في دبي",
      h1sub: "بيع وإيجار | من DIFC إلى الخليج التجاري",
      heroDesc: "يُقدّم سوق المكاتب التجارية في دبي مكاتب من الفئة A في DIFC بإيجار 200 درهم/قدم²/سنة وفرص للتجهيز الخاص.",
      stats: [{ n: "80 درهم", label: "إيجار قدم²/سنة" }, { n: "1500 درهم", label: "سعر البيع/قدم²" }, { n: "6-9%", label: "العائد التجاري" }, { n: "DIFC، الخليج التجاري", label: "أبرز المواقع" }],
      highlights: [
        { title: "مكاتب جاهزة", body: "مكاتب من الفئة A جاهزة للانتقال مع IT والتقسيم والتكييف. DIFC: 160-280 درهم/قدم²/سنة. الخليج التجاري: 80-130 درهم." },
        { title: "مكاتب هيكلية", body: "مكاتب غير مجهَّزة قابلة للتصميم الخاص. سعر الشراء: 1,500-3,000 درهم/قدم². مرونة للشركات النامية." },
        { title: "مكاتب المناطق الحرة", body: "DIFC وDMCC وجبل علي ودبي ساوث: 100% ملكية أجنبية، صفر ضريبة شركات، تحويل كامل للأرباح." },
      ],
      areas: ["DIFC", "الخليج التجاري", "أبراج بحيرة جميرا", "وسط المدينة", "مدينة دبي للإنترنت", "مدينة دبي للإعلام", "ديرة"],
      faqs: [
        { question: "ما أسعار المكاتب التجارية في دبي؟", answer: "الإيجار: DIFC فئة A — 160-280 درهم/قدم²/سنة؛ الخليج التجاري — 80-130؛ JLT — 60-100. الشراء: DIFC — 2,500-5,000 درهم/قدم²؛ الخليج التجاري — 1,500-2,500." },
        { question: "هل يمكن للأجانب تملك مكاتب تجارية في دبي؟", answer: "نعم. في مناطق التملك الحر ومكاتب المناطق الحرة (DIFC، DMCC، JLT) ملكية أجنبية 100% بدون شريك محلي وصفر ضريبة شركات." },
        { question: "ما شروط الإيجار التجاري في دبي؟", answer: "عادةً 1-3 سنوات، سداد بشيكات مؤجلة. مدة الإشعار 90 يومًا. رسوم الخدمة منفصلة: 15-35 درهم/قدم²/سنة." },
      ],
      ctaSearch: "تصفّح المكاتب",
      keywords: ["مكاتب للبيع دبي", "إيجار مكتب دبي", "عقارات تجارية دبي"],
    },
    zh: {
      metaTitle: "迪拜办公室出售与出租 | 商业地产 | Binayah Properties",
      metaDesc: "迪拜商业办公室——DIFC、商业湾、JLT、市中心。精装和毛坯办公室出售与出租。",
      h1: "迪拜办公室",
      h1sub: "出售与出租 | DIFC至商业湾",
      heroDesc: "迪拜商业办公室市场：DIFC A级精装办公室每平方英尺租金200迪拉姆，毛坯办公室供定制装修。",
      stats: [{ n: "80迪拉姆", label: "平方英尺/年租金起" }, { n: "1,500迪拉姆", label: "出售价格起" }, { n: "6-9%", label: "商业收益" }, { n: "DIFC, 商业湾", label: "顶级位置" }],
      highlights: [
        { title: "精装办公室", body: "配备IT、隔断和空调的A级即入住办公室。DIFC：160-280迪拉姆/平方英尺/年。商业湾：80-130迪拉姆。" },
        { title: "毛坯办公室", body: "未装修毛坯办公室，可定制装修。购买价格：1,500-3,000迪拉姆/平方英尺。适合成长中的企业。" },
        { title: "自由区办公室", body: "DIFC、DMCC、杰贝阿里自贸区和迪拜南区办公室：100%外资所有权，零企业税，利润完全汇回。" },
      ],
      areas: ["DIFC", "商业湾", "朱美拉湖塔", "市中心", "迪拜互联网城", "迪拜媒体城", "迪拉"],
      faqs: [
        { question: "迪拜商业办公室的价格是多少？", answer: "租金：DIFC A级160-280迪拉姆/平方英尺/年；商业湾80-130；JLT 60-100。购买：DIFC 2,500-5,000迪拉姆/平方英尺；商业湾1,500-2,500。" },
        { question: "外国人可以在迪拜拥有商业办公室吗？", answer: "可以。外国人可以在自由持有区购买办公室产权。自由区办公室（DIFC、DMCC、JLT）100%外资所有权，无需本地合伙人，零企业税。" },
        { question: "迪拜商业租约的典型条款是什么？", answer: "通常1-3年，以远期支票付款（每年1-4张）。通知期90天。物业服务费另计，通常15-35迪拉姆/平方英尺/年。" },
      ],
      ctaSearch: "浏览办公室",
      keywords: ["迪拜办公室出售", "迪拜办公室出租", "迪拜商业地产"],
    },
  },

  {
    slug: "townhouses",
    searchType: "Villa",
    icon: "🏘️",
    en: {
      metaTitle: "Townhouses for Sale & Rent in Dubai | Family Living | Binayah",
      metaDesc: "Dubai townhouses — 2 to 5-bedroom linked and semi-detached homes in JVC, Town Square, Arabian Ranches. Better value than villas, more space than apartments.",
      h1: "Townhouses in Dubai",
      h1sub: "2–5 Bedrooms | Community Living",
      heroDesc: "Dubai townhouses offer the perfect balance — more space and privacy than apartments, better value than standalone villas. AED 1M–5M across 30+ established communities.",
      stats: [{ n: "AED 1M", label: "Entry Price" }, { n: "1,800–3,500", label: "Avg Sqft" }, { n: "5–7%", label: "Rental Yield" }, { n: "30+", label: "Communities" }],
      highlights: [
        { title: "Affordable Family Homes", body: "3-4 bedroom townhouses from AED 1M–2M in JVC, Town Square, and Mudon. Private garden, parking, community pool — everything a family needs at apartment prices." },
        { title: "Premium Townhouses", body: "4-5 bedroom townhouses in Dubai Hills Estate, Emaar South, and Arabian Ranches 3 from AED 2.5M–5M. Higher specification, premium community amenities." },
        { title: "Investment Townhouses", body: "Townhouses consistently deliver 5–7% gross rental yields. 3-bedroom units in JVC and Town Square rent for AED 80K–120K/year, offering strong income relative to purchase price." },
      ],
      areas: ["Jumeirah Village Circle", "Town Square", "Arabian Ranches", "Dubai Hills Estate", "Mudon", "DAMAC Hills 2", "Emaar South", "Al Furjan"],
      faqs: [
        { question: "What is the price of a townhouse in Dubai?", answer: "Dubai townhouse prices range from AED 1M–1.8M for 2-3 bedroom units in budget communities (Town Square, DAMAC Hills 2) to AED 2.5M–5M for premium 4-5 bedroom townhouses in Dubai Hills Estate and Arabian Ranches. Most off-plan townhouses offer payment plans with 20–40% down payment." },
        { question: "What is the difference between a townhouse and a villa in Dubai?", answer: "Townhouses share one or two walls with neighbouring units (semi-detached or terraced). Villas are fully standalone structures. Townhouses are typically 20–40% less expensive than comparable villas in the same community and offered in smaller plot sizes (1,000–3,000 sqft versus 5,000–15,000+ sqft for villas)." },
        { question: "Which townhouse communities have the best rental yields in Dubai?", answer: "JVC (Jumeirah Village Circle): 5.5–7% gross. Town Square: 5–6.5% gross. DAMAC Hills 2: 5–7%. Mudon: 5.5–6.5%. Yields are generally higher in newer or more suburban communities where purchase prices are lower relative to achievable rents." },
        { question: "Are townhouses a good investment in Dubai 2026?", answer: "Yes. Dubai townhouses have seen 30–50% price appreciation since 2021 in established communities. Supply of community-living properties (townhouses and villas combined) remains well below demand — particularly from families with children relocating to Dubai. Rental demand for 3-4 bedroom family homes is structurally undersupplied." },
      ],
      ctaSearch: "Browse Townhouses",
      keywords: ["townhouses for sale dubai", "townhouse dubai", "buy townhouse dubai", "townhouse rent dubai"],
    },
    ru: {
      metaTitle: "Таунхаусы в Дубае | Продажа и аренда | Семейное жильё | Binayah",
      metaDesc: "Таунхаусы в Дубае — 2-5 спален в JVC, Town Square, Arabian Ranches. Больше пространства, чем в квартире, выгоднее, чем вилла.",
      h1: "Таунхаусы в Дубае",
      h1sub: "2–5 спален | Комьюнити-формат",
      heroDesc: "Таунхаусы Дубая — идеальный баланс: больше места и приватности, чем в квартире, выгоднее отдельной виллы. От 1 до 5 млн AED в 30+ устоявшихся комьюнити.",
      stats: [{ n: "от 1 млн AED", label: "Цена входа" }, { n: "1 800–3 500", label: "Кв. фут в среднем" }, { n: "5–7%", label: "Доходность" }, { n: "30+", label: "Комьюнити" }],
      highlights: [
        { title: "Доступное семейное жильё", body: "Таунхаусы с 3–4 спальнями от 1–2 млн AED в JVC, Town Square и Mudon. Частный сад, парковка, бассейн комьюнити — всё необходимое для семьи по цене апартаментов." },
        { title: "Премиальные таунхаусы", body: "4–5 спален в Dubai Hills Estate, Emaar South и Arabian Ranches 3 от 2,5–5 млн AED. Повышенные характеристики, премиальная инфраструктура." },
        { title: "Инвестиционные таунхаусы", body: "Стабильная доходность 5–7%. 3-комнатные в JVC и Town Square сдаются за 80 000–120 000 AED в год." },
      ],
      areas: ["Джумейра Вилладж Сёркл", "Town Square", "Arabian Ranches", "Dubai Hills Estate", "Mudon", "DAMAC Hills 2", "Emaar South", "Al Furjan"],
      faqs: [
        { question: "Какова цена таунхауса в Дубае?", answer: "Таунхаусы в Дубае: от 1–1,8 млн AED за 2–3 спальни в бюджетных комьюнити (Town Square, DAMAC Hills 2) до 2,5–5 млн AED за 4–5 спален в Dubai Hills Estate и Arabian Ranches." },
        { question: "В чём разница между таунхаусом и виллой в Дубае?", answer: "Таунхаусы имеют одну или две общие стены с соседними домами. Виллы полностью отдельностоящие. Таунхаусы обычно на 20–40% дешевле сопоставимых вилл в том же комьюнити." },
        { question: "Таунхаус в Дубае — хорошая инвестиция?", answer: "Да. Таунхаусы в устоявшихся комьюнити выросли на 30–50% с 2021 года. Спрос на семейное жильё с 3–4 спальнями структурно превышает предложение." },
      ],
      ctaSearch: "Смотреть таунхаусы",
      keywords: ["таунхаус дубай", "купить таунхаус дубай", "аренда таунхауса дубай"],
    },
    ar: {
      metaTitle: "تاون هاوس للبيع والإيجار في دبي | بناية للعقارات",
      metaDesc: "تاون هاوس في دبي — 2 إلى 5 غرف في JVC وتاون سكوير وأراضي الخيل. مساحة أكبر من الشقق وسعر أفضل من الفلل.",
      h1: "تاون هاوس في دبي",
      h1sub: "2-5 غرف | معيشة مجتمعية",
      heroDesc: "يُقدّم التاون هاوس في دبي التوازن المثالي — مساحة وخصوصية أكبر من الشقق وقيمة أفضل من الفلل المستقلة.",
      stats: [{ n: "1M درهم", label: "سعر البداية" }, { n: "1800-3500", label: "متوسط القدم²" }, { n: "5-7%", label: "العائد الإيجاري" }, { n: "+30", label: "مجتمعًا" }],
      highlights: [
        { title: "منازل عائلية بأسعار معقولة", body: "تاون هاوس بـ 3-4 غرف من 1-2 مليون درهم في JVC وتاون سكوير وموادون. حديقة خاصة ومواقف ومسبح — كل ما تحتاجه العائلة." },
        { title: "تاون هاوس متميزة", body: "4-5 غرف في دبي هيلز وإعمار ساوث وأراضي الخيل 3 من 2.5-5 ملايين درهم." },
        { title: "تاون هاوس استثمارية", body: "عوائد إيجارية ثابتة 5-7%. وحدات بـ 3 غرف في JVC وتاون سكوير تُؤجَّر بـ 80,000-120,000 درهم سنويًا." },
      ],
      areas: ["جميرا فيلدج سيركل", "تاون سكوير", "أراضي الخيل", "دبي هيلز إستيت", "موادون", "داماك هيلز 2", "إعمار ساوث", "الفرجان"],
      faqs: [
        { question: "ما سعر التاون هاوس في دبي؟", answer: "من 1-1.8 مليون درهم لـ 2-3 غرف في المجتمعات الاقتصادية إلى 2.5-5 ملايين لـ 4-5 غرف في دبي هيلز وأراضي الخيل." },
        { question: "ما الفرق بين التاون هاوس والفيلا في دبي؟", answer: "التاون هاوس يشترك في جدار واحد أو اثنين مع الجيران. الفيلا مستقلة تمامًا. عادةً التاون هاوس أرخص 20-40% من الفلل المماثلة في نفس المجتمع." },
        { question: "هل التاون هاوس استثمار جيد في 2026؟", answer: "نعم. ارتفعت أسعار التاون هاوس في المجتمعات الراسخة 30-50% منذ 2021. الطلب على المنازل العائلية بـ 3-4 غرف يفوق العرض بشكل هيكلي." },
      ],
      ctaSearch: "تصفّح التاون هاوس",
      keywords: ["تاون هاوس للبيع دبي", "إيجار تاون هاوس دبي", "شراء تاون هاوس دبي"],
    },
    zh: {
      metaTitle: "迪拜联排别墅出售与出租 | 家庭社区 | Binayah Properties",
      metaDesc: "迪拜联排别墅——JVC、Town Square、Arabian Ranches，2至5卧室。比公寓更多空间，比独栋别墅更实惠。",
      h1: "迪拜联排别墅",
      h1sub: "2-5卧室 | 社区生活",
      heroDesc: "迪拜联排别墅实现完美平衡——比公寓更多空间和私密性，比独栋别墅更具性价比，100万-500万迪拉姆，遍布30多个成熟社区。",
      stats: [{ n: "100万AED", label: "入市价格" }, { n: "1,800-3,500", label: "平均平方英尺" }, { n: "5-7%", label: "租金收益" }, { n: "30+", label: "社区" }],
      highlights: [
        { title: "经济型家庭住宅", body: "JVC、Town Square和Mudon的3-4卧室联排别墅，起价100-200万迪拉姆。私人花园、停车位、社区泳池——以公寓价格满足家庭全部需求。" },
        { title: "高端联排别墅", body: "迪拜山庄、Emaar South和Arabian Ranches 3的4-5卧室联排别墅，250-500万迪拉姆，更高规格，顶级社区配套。" },
        { title: "投资型联排别墅", body: "持续提供5-7%毛收益率。JVC和Town Square的3卧室单元年租金8-12万迪拉姆，相对购买价格提供强劲收入。" },
      ],
      areas: ["朱美拉村庄圈", "Town Square", "Arabian Ranches", "迪拜山庄", "Mudon", "DAMAC Hills 2", "Emaar South", "Al Furjan"],
      faqs: [
        { question: "迪拜联排别墅的价格是多少？", answer: "预算型社区（Town Square、DAMAC Hills 2）2-3卧室100-180万迪拉姆；迪拜山庄和Arabian Ranches高端4-5卧室250-500万迪拉姆。" },
        { question: "迪拜联排别墅和独栋别墅有什么区别？", answer: "联排别墅与相邻单元共享一至两面墙（半独立或排屋），独栋别墅完全独立。联排别墅通常比同社区可比别墅便宜20-40%。" },
        { question: "2026年迪拜联排别墅是好的投资吗？", answer: "是的。成熟社区联排别墅自2021年以来升值30-50%。3-4卧室家庭住宅的需求结构性超过供应。" },
      ],
      ctaSearch: "浏览联排别墅",
      keywords: ["迪拜联排别墅出售", "迪拜联排别墅出租", "购买迪拜联排别墅"],
    },
  },

  {
    slug: "warehouses",
    searchType: "Commercial",
    icon: "🏭",
    en: {
      metaTitle: "Warehouses for Sale & Rent in Dubai | Industrial Property | Binayah",
      metaDesc: "Industrial warehouses in Dubai — Al Quoz, Jebel Ali, Dubai South, DIC. Logistics, storage, and manufacturing spaces for lease and purchase. Binayah commercial.",
      h1: "Warehouses in Dubai",
      h1sub: "Industrial & Logistics | Al Quoz to Jebel Ali",
      heroDesc: "Dubai's logistics hub status makes it one of the Middle East's most active industrial property markets. Warehouses from AED 60/sqft rent in Al Quoz to AED 35/sqft in Jebel Ali Free Zone.",
      stats: [{ n: "AED 35/sqft", label: "Rent from/Year" }, { n: "AED 400/sqft", label: "Purchase from" }, { n: "7–10%", label: "Industrial Yield" }, { n: "Jebel Ali FZ", label: "Largest Hub" }],
      highlights: [
        { title: "Standard Storage Warehouses", body: "Al Quoz and Dubai Investment Park offer standard 5,000–50,000 sqft warehouses with 6–9m clear heights, loading docks, and mezzanine offices. Rent: AED 50–80/sqft/year." },
        { title: "Free Zone Warehouses", body: "Jebel Ali Free Zone (JAFZA) and Dubai South Free Zone warehouses allow 100% foreign ownership, re-export without duty, and direct port/airport access. Rent: AED 35–55/sqft/year." },
        { title: "Cold Storage & Specialist", body: "Temperature-controlled and pharmaceutical warehouses in Al Quoz and Dubai Industrial Park command 20–40% premium over standard warehouse rents due to fit-out investment." },
      ],
      areas: ["Al Quoz", "Jebel Ali Free Zone", "Dubai Industrial Park", "Dubai South", "Dubai Investment Park", "Ras Al Khor", "Al Qusais"],
      faqs: [
        { question: "What are industrial warehouse rents in Dubai?", answer: "Al Quoz: AED 50–80/sqft/year for standard warehouses. DIP (Dubai Investment Park): AED 40–60/sqft/year. Jebel Ali Free Zone: AED 35–55/sqft/year. Dubai South: AED 30–50/sqft/year. Specialist or cold-store warehouses command 20–40% premium." },
        { question: "Can foreign companies own warehouses in Dubai?", answer: "In free zones (Jebel Ali, Dubai South, Dubai Airport Free Zone): yes, 100% foreign ownership with no local partner required. In mainland areas (Al Quoz, DIP): UAE commercial regulations apply — foreign businesses typically use a local agent structure or a LLC with Emirati partner, though the Companies Law reform now allows 100% foreign ownership in most activities." },
        { question: "What is the minimum warehouse size for rent in Dubai?", answer: "Minimum warehouse sizes in Dubai typically start from 2,000–3,000 sqft in older Al Quoz buildings. Most modern logistics parks (DIP, Dubai South) require minimum commitments of 10,000–25,000 sqft. Sub-lease opportunities in established warehouses can offer smaller units." },
      ],
      ctaSearch: "Browse Warehouses",
      keywords: ["warehouse for rent dubai", "warehouse for sale dubai", "industrial property dubai", "al quoz warehouse"],
    },
    ru: {
      metaTitle: "Склады в Дубае | Аренда и продажа | Промышленная недвижимость | Binayah",
      metaDesc: "Промышленные склады в Дубае — Аль-Куз, Джебель Али, Дубай Саут. Логистика, хранение и производство для аренды и покупки.",
      h1: "Склады в Дубае",
      h1sub: "Промышленная и логистическая | Аль-Куз–Джебель Али",
      heroDesc: "Статус логистического хаба Дубая делает его одним из самых активных рынков промышленной недвижимости на Ближнем Востоке. Склады от 35 AED/кв. фут аренды в год.",
      stats: [{ n: "от 35 AED", label: "Аренда кв. фут/год" }, { n: "от 400 AED", label: "Цена покупки" }, { n: "7–10%", label: "Промышленная доходность" }, { n: "Jebel Ali FZ", label: "Крупнейший хаб" }],
      highlights: [
        { title: "Стандартные склады", body: "Аль-Куз и Дубайский инвестиционный парк: склады 5 000–50 000 кв. фут, высота 6–9 м, погрузочные доки. Аренда: 50–80 AED/кв. фут/год." },
        { title: "Склады в свободных зонах", body: "JAFZA и Дубай Саут: 100% иностранное владение, реэкспорт без пошлин, прямой доступ к порту и аэропорту. Аренда: 35–55 AED/кв. фут/год." },
        { title: "Специализированные склады", body: "Склады с температурным контролем и фармацевтические хранилища — надбавка 20–40% к стандартным ставкам." },
      ],
      areas: ["Аль-Куз", "Джебель Али Фри Зон", "Дубайский промышленный парк", "Дубай Саут", "DIP", "Рас-Аль-Хор", "Аль-Кусейс"],
      faqs: [
        { question: "Каковы ставки аренды склада в Дубае?", answer: "Аль-Куз: 50–80 AED/кв. фут/год. DIP: 40–60. Джебель Али Фри Зон: 35–55. Дубай Саут: 30–50. Специализированные/холодильные — надбавка 20–40%." },
        { question: "Могут ли иностранные компании владеть складами в Дубае?", answer: "В свободных зонах (Джебель Али, Дубай Саут) — да, 100% иностранное владение без местного партнёра. На материковой части — применяются коммерческие правила ОАЭ." },
      ],
      ctaSearch: "Смотреть склады",
      keywords: ["склад дубай", "аренда склада дубай", "промышленная недвижимость дубай"],
    },
    ar: {
      metaTitle: "مستودعات للبيع والإيجار في دبي | عقارات صناعية | بناية",
      metaDesc: "مستودعات صناعية في دبي — القوز وجبل علي ودبي ساوث. مساحات للوجستية وتخزين وتصنيع.",
      h1: "مستودعات في دبي",
      h1sub: "صناعي ولوجستي | القوز إلى جبل علي",
      heroDesc: "مكانة دبي كمركز لوجستي تجعلها من أكثر أسواق العقارات الصناعية نشاطًا في الشرق الأوسط.",
      stats: [{ n: "35 درهم", label: "إيجار قدم²/سنة" }, { n: "400 درهم", label: "سعر الشراء" }, { n: "7-10%", label: "العائد الصناعي" }, { n: "منطقة جبل علي", label: "أكبر مركز" }],
      highlights: [
        { title: "مستودعات قياسية", body: "القوز ودبي للاستثمار: مستودعات 5,000-50,000 قدم² بارتفاع 6-9 م وأرصفة تحميل. الإيجار: 50-80 درهم/قدم²/سنة." },
        { title: "مستودعات المناطق الحرة", body: "JAFZA ودبي ساوث: 100% ملكية أجنبية، إعادة تصدير بدون جمارك، وصول مباشر للميناء والمطار." },
        { title: "مستودعات متخصصة", body: "التخزين المبرد والمستودعات الصيدلانية تحقق علاوة 20-40% على الأسعار القياسية." },
      ],
      areas: ["القوز", "المنطقة الحرة بجبل علي", "دبي الصناعية", "دبي ساوث", "دبي للاستثمار", "رأس الخور", "القصيص"],
      faqs: [
        { question: "ما إيجارات المستودعات الصناعية في دبي؟", answer: "القوز: 50-80 درهم/قدم²/سنة. دبي للاستثمار: 40-60. جبل علي الحرة: 35-55. دبي ساوث: 30-50." },
        { question: "هل يمكن للشركات الأجنبية تملك مستودعات في دبي؟", answer: "في المناطق الحرة (جبل علي، دبي ساوث): نعم، ملكية أجنبية 100% بدون شريك محلي." },
      ],
      ctaSearch: "تصفّح المستودعات",
      keywords: ["مستودع للإيجار دبي", "مستودع للبيع دبي", "عقارات صناعية دبي"],
    },
    zh: {
      metaTitle: "迪拜仓库出售与出租 | 工业地产 | Binayah Properties",
      metaDesc: "迪拜工业仓库——Al Quoz、杰贝阿里、迪拜南区。物流、仓储和制造空间出租与购买。",
      h1: "迪拜仓库",
      h1sub: "工业与物流 | Al Quoz至杰贝阿里",
      heroDesc: "迪拜的物流枢纽地位使其成为中东最活跃的工业地产市场之一。",
      stats: [{ n: "35迪拉姆", label: "租金/平方英尺/年起" }, { n: "400迪拉姆", label: "购买价格起" }, { n: "7-10%", label: "工业收益率" }, { n: "杰贝阿里自贸区", label: "最大枢纽" }],
      highlights: [
        { title: "标准储存仓库", body: "Al Quoz和迪拜投资园区：5,000-50,000平方英尺仓库，层高6-9米，装卸码头。租金：50-80迪拉姆/平方英尺/年。" },
        { title: "自贸区仓库", body: "杰贝阿里自贸区和迪拜南区：100%外资所有权，免税再出口，直达港口和机场。租金：35-55迪拉姆/平方英尺/年。" },
        { title: "专用仓库", body: "温控和医药仓库比标准仓库租金高20-40%。" },
      ],
      areas: ["Al Quoz", "杰贝阿里自贸区", "迪拜工业园区", "迪拜南区", "迪拜投资园区", "Ras Al Khor", "Al Qusais"],
      faqs: [
        { question: "迪拜工业仓库的租金是多少？", answer: "Al Quoz：50-80迪拉姆/平方英尺/年。迪拜投资园区：40-60。杰贝阿里自贸区：35-55。迪拜南区：30-50。" },
        { question: "外资企业可以在迪拜拥有仓库吗？", answer: "在自贸区（杰贝阿里、迪拜南区）：是的，100%外资所有权，无需本地合伙人。" },
      ],
      ctaSearch: "浏览仓库",
      keywords: ["迪拜仓库出租", "迪拜仓库出售", "迪拜工业地产"],
    },
  },

  {
    slug: "land-for-sale",
    searchType: "Plot",
    icon: "🌿",
    en: {
      metaTitle: "Land & Plots for Sale in Dubai | Freehold | Binayah Properties",
      metaDesc: "Residential and commercial land for sale in Dubai. Freehold plots in Jumeirah, MBR City, Tilal Al Ghaf, Al Barari. GFA approval, clean title. Binayah Properties.",
      h1: "Land for Sale in Dubai",
      h1sub: "Residential & Commercial Plots | Freehold",
      heroDesc: "Dubai's land market offers rare freehold plots in established and emerging communities. Build your custom villa or develop a commercial project on one of the world's most dynamic urban canvases.",
      stats: [{ n: "AED 200/sqft", label: "Residential Entry" }, { n: "AED 400/sqft", label: "Premium Locations" }, { n: "3,000+", label: "Min Plot (sqft)" }, { n: "MBR City", label: "Largest Supply" }],
      highlights: [
        { title: "Residential Plots", body: "Build your custom villa on freehold land in Jumeirah, Al Barari, Nad Al Sheba, and Mohammed Bin Rashid City (MBR). Prices from AED 200/sqft to AED 1,000/sqft in prime beachfront areas." },
        { title: "Commercial & Mixed-Use", body: "Development plots in Business Bay, Dubai South, and Jebel Ali for commercial, residential, or mixed-use projects. Typically sold with approved GFA (Gross Floor Area) permissions." },
        { title: "Industrial Land", body: "Industrial-zoned plots in Al Quoz, Dubai Investment Park, and Dubai South for warehousing or manufacturing. From AED 50/sqft with long-term usufruct rights." },
      ],
      areas: ["Jumeirah", "Mohammed Bin Rashid City", "Al Barari", "Tilal Al Ghaf", "Nad Al Sheba", "Dubai Hills Estate", "Hatta", "Dubai South"],
      faqs: [
        { question: "Can foreigners buy land in Dubai?", answer: "Yes, in designated freehold zones. Foreigners can purchase freehold land in areas including MBR City, Jumeirah Village Circle, Business Bay, Dubai South, and others. Key exceptions: Jumeirah (the traditional residential area) and some older areas are leasehold. Always verify freehold status before purchase." },
        { question: "What is the process for buying land in Dubai?", answer: "1) Agree price and terms with seller. 2) Sign MOU and pay 10% deposit. 3) NOC from developer (if masterplan land). 4) Ensure plot has approved GFA/FAR ratio (Floor Area Ratio). 5) DLD transfer with 4% transfer fee. 6) Apply to Dubai Municipality or relevant authority for building permit." },
        { question: "What can I build on freehold land in Dubai?", answer: "Use permissions depend on the zoning classification (residential, commercial, mixed-use, industrial). Residential G+1 or G+2 in most villa communities. MBR City allows G+3 to G+5 in some plots. Always check the approved GFA and setback requirements before purchase." },
        { question: "What is the price per sqft for land in Dubai?", answer: "Varies enormously by location. Residential land: AED 200–400/sqft (suburban), AED 500–1,000/sqft (prime Jumeirah/waterfront). Commercial land: AED 400–2,000/sqft (Business Bay, DIFC fringe). Industrial/logistics: AED 50–150/sqft." },
      ],
      ctaSearch: "Browse Land & Plots",
      keywords: ["land for sale dubai", "plot for sale dubai", "freehold land dubai", "buy land dubai", "residential plot dubai"],
    },
    ru: {
      metaTitle: "Земельные участки в Дубае | Продажа фрихолд | Binayah",
      metaDesc: "Жилые и коммерческие земельные участки в Дубае. Фрихолд-участки в Джумейре, MBR City, Tilal Al Ghaf. Чистый правоустанавливающий документ.",
      h1: "Земельные участки в Дубае",
      h1sub: "Жилые и коммерческие | Фрихолд",
      heroDesc: "Рынок земли Дубая предлагает редкие фрихолд-участки в устоявшихся и развивающихся комьюнити. Постройте собственную виллу или реализуйте коммерческий проект.",
      stats: [{ n: "от 200 AED", label: "Жилые кв. фут" }, { n: "от 400 AED", label: "Премиальные локации" }, { n: "3 000+", label: "Мин. участок кв. фут" }, { n: "MBR City", label: "Наибольшее предложение" }],
      highlights: [
        { title: "Жилые участки", body: "Стройте виллу на фрихолд-земле в Джумейре, Аль-Барари, Над Аль-Шеба и MBR City. Цены от 200 до 1 000+ AED/кв. фут в прибрежных районах." },
        { title: "Коммерческие и многофункциональные", body: "Участки под застройку в Бизнес-Бей, Дубай Саут и Джебель Али под коммерческие, жилые или многофункциональные проекты." },
        { title: "Промышленная земля", body: "Промышленные участки в Аль-Куз, DIP и Дубай Саут для складов и производства. От 50 AED/кв. фут." },
      ],
      areas: ["Джумейра", "MBR City", "Аль-Барари", "Tilal Al Ghaf", "Нид Аль-Шеба", "Dubai Hills Estate", "Хатта", "Дубай Саут"],
      faqs: [
        { question: "Могут ли иностранцы покупать землю в Дубае?", answer: "Да, в специальных фрихолд-зонах: MBR City, JVC, Бизнес-Бей, Дубай Саут и других. Традиционные районы Джумейры в основном — лизхолд. Всегда уточняйте статус у агента Binayah перед покупкой." },
        { question: "Какова цена за кв. фут земли в Дубае?", answer: "Жилые участки: 200–400 AED/кв. фут (пригороды), 500–1 000+ AED/кв. фут (премиальные прибрежные). Коммерческие: 400–2 000 AED/кв. фут. Промышленные: 50–150 AED/кв. фут." },
      ],
      ctaSearch: "Смотреть участки",
      keywords: ["земельный участок дубай", "купить землю дубай", "участок под строительство дубай"],
    },
    ar: {
      metaTitle: "أراضي للبيع في دبي | تملك حر | بناية للعقارات",
      metaDesc: "أراضٍ سكنية وتجارية للبيع في دبي. قطع أرضية تملك حر في جميرا ومدينة محمد بن راشد وتلال الغاف.",
      h1: "أراضي للبيع في دبي",
      h1sub: "أراضٍ سكنية وتجارية | تملك حر",
      heroDesc: "يُقدّم سوق الأراضي في دبي قطعًا نادرة بتملك حر في مجتمعات راسخة وناشئة. ابنِ فيلتك الخاصة أو طوّر مشروعًا تجاريًا.",
      stats: [{ n: "200 درهم/قدم²", label: "سعر السكني" }, { n: "400 درهم/قدم²", label: "المواقع المتميزة" }, { n: "+3000", label: "أدنى مساحة (قدم²)" }, { n: "MBR City", label: "أكبر معروض" }],
      highlights: [
        { title: "أراضٍ سكنية", body: "ابنِ فيلتك على أراضٍ تملك حر في جميرا والبراري ونيد الشبا ومدينة محمد بن راشد. الأسعار من 200 إلى 1,000+ درهم/قدم² في المناطق الساحلية." },
        { title: "تجارية ومتعددة الاستخدام", body: "قطع للتطوير في الخليج التجاري ودبي ساوث وجبل علي للمشاريع التجارية أو السكنية أو المتعددة." },
        { title: "أراضٍ صناعية", body: "أراضٍ مخصصة للصناعة في القوز ودبي للاستثمار ودبي ساوث. من 50 درهم/قدم²." },
      ],
      areas: ["جميرا", "مدينة محمد بن راشد", "البراري", "تلال الغاف", "نيد الشبا", "دبي هيلز إستيت", "حتا", "دبي ساوث"],
      faqs: [
        { question: "هل يمكن للأجانب شراء أراضٍ في دبي؟", answer: "نعم، في مناطق التملك الحر المخصصة: مدينة محمد بن راشد وJVC والخليج التجاري ودبي ساوث وغيرها. بعض مناطق جميرا التقليدية حكر. تحقق دائمًا من الوضع القانوني قبل الشراء." },
        { question: "ما سعر القدم المربعة للأراضي في دبي؟", answer: "الأراضي السكنية: 200-400 درهم/قدم² (الضواحي)، 500-1,000+ درهم/قدم² (الساحل المتميز). التجارية: 400-2,000 درهم/قدم². الصناعية: 50-150 درهم/قدم²." },
      ],
      ctaSearch: "تصفّح الأراضي",
      keywords: ["أراضي للبيع دبي", "قطعة أرض دبي", "شراء أرض دبي"],
    },
    zh: {
      metaTitle: "迪拜土地出售 | 自由持有地块 | Binayah Properties",
      metaDesc: "迪拜住宅和商业土地出售。朱美拉、MBR城、Tilal Al Ghaf自由持有地块。产权清晰。",
      h1: "迪拜土地出售",
      h1sub: "住宅和商业地块 | 自由持有",
      heroDesc: "迪拜土地市场在成熟和新兴社区提供稀缺自由持有地块。建造您的定制别墅或在全球最具活力的城市画布上开发商业项目。",
      stats: [{ n: "200迪拉姆", label: "住宅起价/平方英尺" }, { n: "400迪拉姆", label: "优质地块" }, { n: "3,000+", label: "最小地块(平方英尺)" }, { n: "MBR城", label: "最大供应量" }],
      highlights: [
        { title: "住宅地块", body: "在朱美拉、Al Barari、Nad Al Sheba和MBR城购买自由持有土地建造定制别墅。价格从200迪拉姆到滨水优质地块1,000迪拉姆以上/平方英尺。" },
        { title: "商业和综合用途", body: "商业湾、迪拜南区和杰贝阿里的开发地块，适用于商业、住宅或综合项目。通常附带已批准的建筑面积许可。" },
        { title: "工业用地", body: "Al Quoz、迪拜投资园区和迪拜南区的工业区划地块，适用于仓储或制造。每平方英尺50迪拉姆起。" },
      ],
      areas: ["朱美拉", "MBR城", "Al Barari", "Tilal Al Ghaf", "Nad Al Sheba", "迪拜山庄", "哈塔", "迪拜南区"],
      faqs: [
        { question: "外国人可以在迪拜购买土地吗？", answer: "是的，在指定自由持有区：MBR城、朱美拉村庄圈、商业湾、迪拜南区等。传统朱美拉部分区域为租赁权。购买前务必核实产权状态。" },
        { question: "迪拜土地的每平方英尺价格是多少？", answer: "住宅用地：郊区200-400迪拉姆/平方英尺，优质滨水地块500-1,000迪拉姆以上。商业用地：400-2,000迪拉姆。工业用地：50-150迪拉姆。" },
      ],
      ctaSearch: "浏览土地地块",
      keywords: ["迪拜土地出售", "迪拜地块出售", "购买迪拜土地", "迪拜住宅地块"],
    },
  },
];

export function findPropertyTypePage(slug: string): PropertyTypePage | undefined {
  return PROPERTY_TYPE_PAGES.find(p => p.slug === slug);
}
