import { config } from "dotenv";
import mongoose from "mongoose";
import Project from "../models/Project";

// Load .env.local since this runs outside Next.js
config({ path: ".env.local" });

const MONGODB_URI = process.env.MONGODB_URI || "mongodb://localhost:27017/binayah";

const seedProjects = [
  {
    name: 'Marina Gate Tower 3',
    slug: 'marina-gate-tower-3',
    status: 'Off-Plan',
    projectType: 'Residential',
    propertyType: 'Apartment',
    developerName: 'Select Group',
    community: 'Dubai Marina',
    city: 'Dubai',
    country: 'UAE',
    locationDescription: 'Situated at the heart of Dubai Marina, Marina Gate Tower 3 offers panoramic views of the marina skyline and direct access to Dubai Marina Mall.',
    googleMapsUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3613.5!2d55.135!3d25.077',
    latitude: 25.077,
    longitude: 55.135,
    startingPrice: 1850000,
    currency: 'AED',
    priceRange: 'AED 1.85M - AED 8.5M',
    titleType: 'Freehold',
    ownershipEligibility: 'All Nationalities',
    completionDate: new Date('2027-06-30'),
    constructionStatus: 'Under Construction — 45% Complete',
    downPayment: '10%',
    paymentPlanSummary: '60/40 Payment Plan',
    paymentPlanDetails: '10% on booking, 50% during construction in installments, 40% on handover.',
    unitTypes: ["Studio", "1 Bedroom", "2 Bedrooms", "3 Bedrooms", "Penthouse"],
    unitSizeMin: 450,
    unitSizeMax: 4200,
    availabilityStatus: 'Available',
    totalUnits: 420,
    shortOverview: 'Luxury waterfront living in the heart of Dubai Marina with world-class amenities and stunning marina views.',
    fullDescription: 'Marina Gate Tower 3 by Select Group is the final chapter of the iconic Marina Gate trilogy. Rising 65 stories above Dubai Marina, this architectural masterpiece redefines luxury waterfront living.',
    targetBuyers: ["End Users", "Investors", "Families", "Couples"],
    investmentHighlights: ["Prime waterfront location", "High rental demand area", "Golden Visa eligible", "Tax-free returns", "Strong capital appreciation", "World-class amenities"],
    keyHighlights: ["65-storey iconic tower", "Panoramic marina & sea views", "Direct mall access via sky bridge", "Infinity pool on podium level", "Smart home technology", "Concierge & valet service"],
    amenities: ["Infinity Pool", "Gymnasium", "Kids Play Area", "Concierge Service", "Valet Parking", "24/7 Security", "Spa & Sauna", "BBQ Terrace", "Jogging Track", "Retail Outlets", "Landscaped Gardens", "Smart Home"],
    nearbyAttractions: [{"name": "Dubai Marina Mall", "type": "mall", "distance": "2 min walk"}, {"name": "JBR Beach", "type": "beach", "distance": "8 min walk"}, {"name": "DMCC Metro", "type": "transport", "distance": "5 min walk"}, {"name": "Dubai Airport", "type": "airport", "distance": "25 min drive"}, {"name": "Palm Jumeirah", "type": "landmark", "distance": "10 min drive"}, {"name": "Marina Walk", "type": "park", "distance": "1 min walk"}],
    imageGallery: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&h=800&fit=crop", "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&h=800&fit=crop", "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&h=800&fit=crop", "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&h=800&fit=crop"],
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    faqs: [{"question": "What is the payment plan?", "answer": "60/40 \u2014 10% on booking, 50% during construction, 40% on handover."}, {"question": "Is this Golden Visa eligible?", "answer": "Yes, units valued at AED 2M+ qualify for the UAE Golden Visa."}, {"question": "What are service charges?", "answer": "Approximately AED 14-16 per sqft annually."}, {"question": "When is handover?", "answer": "Expected Q2 2027."}, {"question": "Can I get a mortgage?", "answer": "Yes, several UAE banks offer mortgages for off-plan with 50% construction completion."}],
    ctaHeadline: 'Invest in Marina Gate Tower 3',
    ctaSubheadline: 'Premium waterfront apartments from AED 1.85M.',
    metaTitle: 'Marina Gate Tower 3 | Dubai Marina | Binayah',
    metaDescription: 'Marina Gate Tower 3 by Select Group. Luxury waterfront apartments from AED 1.85M. 60/40 payment plan.',
    publishStatus: 'Published',
  },
  {
    name: 'The Acres by Meraas',
    slug: 'the-acres-by-meraas',
    status: 'New Launch',
    projectType: 'Residential',
    propertyType: 'Villa',
    developerName: 'Meraas',
    community: 'Dubailand',
    startingPrice: 3200000,
    priceRange: 'AED 3.2M - AED 6.5M',
    completionDate: new Date('2028-03-31'),
    constructionStatus: 'Early Construction — 10% Complete',
    downPayment: '10%',
    paymentPlanSummary: '80/20 Payment Plan',
    paymentPlanDetails: '10% on booking, 70% during construction quarterly, 20% on handover.',
    unitTypes: ["3 Bedrooms", "4 Bedrooms", "5 Bedrooms"],
    unitSizeMin: 2800,
    unitSizeMax: 5500,
    totalUnits: 640,
    shortOverview: 'Nature-inspired luxury villas by Meraas with private gardens, community parks, and family amenities.',
    fullDescription: 'The Acres by Meraas is a master-planned villa community celebrating modern architecture and nature. 10+ parks, international schools, and retail — everything within walking distance.',
    targetBuyers: ["End Users", "Families"],
    investmentHighlights: ["Meraas premium quality", "Master-planned community", "Below market launch price", "Strong family demand"],
    keyHighlights: ["Private gardens", "10+ community parks", "International schools", "Smart & sustainable design", "Rooftop terraces", "Pet-friendly"],
    amenities: ["Community Pool", "Gymnasium", "Kids Play Areas", "Parks", "Sports Courts", "Cycling Tracks", "Retail Center", "Mosque", "Medical Center", "School"],
    nearbyAttractions: [{"name": "Global Village", "type": "entertainment", "distance": "10 min drive"}, {"name": "Dubai Outlet Mall", "type": "mall", "distance": "12 min drive"}, {"name": "IMG Worlds", "type": "theme park", "distance": "8 min drive"}],
    imageGallery: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&h=800&fit=crop", "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&h=800&fit=crop", "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&h=800&fit=crop"],
    faqs: [{"question": "What sizes are available?", "answer": "3BR (2,800sqft), 4BR (3,800sqft), 5BR (5,500sqft)."}, {"question": "Are pets allowed?", "answer": "Yes, pet-friendly community with dedicated walking areas."}],
    ctaHeadline: 'Your Family Home Awaits',
    metaTitle: 'The Acres by Meraas | Villas in Dubailand | Binayah',
    publishStatus: 'Published',
  },
  {
    name: 'Creek Views by Azizi',
    slug: 'creek-views-by-azizi',
    status: 'Off-Plan',
    propertyType: 'Apartment',
    developerName: 'Azizi Developments',
    community: 'Dubai Healthcare City',
    startingPrice: 850000,
    priceRange: 'AED 850K - AED 2.8M',
    completionDate: new Date('2026-12-31'),
    constructionStatus: 'Under Construction — 70% Complete',
    downPayment: '20%',
    paymentPlanSummary: '60/40 Payment Plan',
    unitTypes: ["Studio", "1 Bedroom", "2 Bedrooms", "3 Bedrooms"],
    unitSizeMin: 380,
    unitSizeMax: 2100,
    totalUnits: 780,
    availabilityStatus: 'Limited',
    shortOverview: 'Affordable luxury apartments overlooking Dubai Creek with 7-8% rental yield potential.',
    fullDescription: 'Creek Views by Azizi offers affordability and luxury in Dubai Healthcare City. Creek views, proximity to Downtown, and excellent connectivity — ideal for investors seeking strong rental returns.',
    targetBuyers: ["Investors", "First-Time Buyers", "Couples"],
    investmentHighlights: ["High rental yield 7-8%", "Below market entry", "Near Downtown", "Strong tenant demand", "Golden Visa eligible (2BR+)"],
    keyHighlights: ["Creek & Burj Khalifa views", "Walking to Metro", "7-8% rental yield", "Premium finishes", "Below market price"],
    amenities: ["Swimming Pool", "Gymnasium", "Children's Play Area", "BBQ Area", "Retail", "Gardens", "Covered Parking", "24/7 Security"],
    nearbyAttractions: [{"name": "Dubai Mall", "type": "mall", "distance": "10 min drive"}, {"name": "Burj Khalifa", "type": "landmark", "distance": "12 min drive"}, {"name": "DHCC Metro", "type": "transport", "distance": "4 min walk"}],
    imageGallery: ["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&h=800&fit=crop", "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1200&h=800&fit=crop", "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&h=800&fit=crop"],
    faqs: [{"question": "What rental yield?", "answer": "Studios and 1BRs achieve 7-8% gross \u2014 among the highest in Dubai."}, {"question": "When is handover?", "answer": "Q4 2026. Construction is 70% complete."}],
    ctaHeadline: 'Smart Investment from AED 850K',
    metaTitle: 'Creek Views by Azizi | Apartments from AED 850K | Binayah',
    publishStatus: 'Published',
  },
  {
    name: 'Burj Binghatti Jacob & Co',
    slug: 'burj-binghatti-jacob-and-co',
    status: 'Off-Plan',
    propertyType: 'Apartment',
    developerName: 'Binghatti',
    community: 'Business Bay',
    startingPrice: 2400000,
    priceRange: 'AED 2.4M - AED 50M+',
    completionDate: new Date('2028-12-31'),
    constructionStatus: 'Early Construction — 15% Complete',
    downPayment: '20%',
    paymentPlanSummary: '70/30 Payment Plan',
    unitTypes: ["1 Bedroom", "2 Bedrooms", "3 Bedrooms", "4 Bedrooms", "Penthouse", "Duplex"],
    unitSizeMin: 750,
    unitSizeMax: 15000,
    totalUnits: 300,
    shortOverview: 'Ultra-luxury branded residences by Binghatti and Jacob & Co — the world\'s tallest residential clock tower.',
    fullDescription: 'Rising 100+ stories above Business Bay, this branded collaboration brings Jacob & Co\'s legendary craftsmanship to residential living. Bespoke finishes, panoramic views, world\'s highest infinity pool.',
    targetBuyers: ["UHNW Individuals", "Investors", "Luxury Buyers"],
    investmentHighlights: ["Branded residence premium", "Iconic 100+ storey tower", "World's highest infinity pool", "Ultra-limited supply"],
    keyHighlights: ["100+ storey landmark", "Jacob & Co interiors", "Highest infinity pool", "Private members club", "Michelin restaurant", "Full-floor wellness spa"],
    amenities: ["Infinity Pool", "Private Members Club", "Michelin Restaurant", "Wellness Spa", "Cigar Lounge", "Wine Cellar", "Private Cinema", "Concierge", "Helipad"],
    nearbyAttractions: [{"name": "Dubai Mall", "type": "mall", "distance": "5 min drive"}, {"name": "Burj Khalifa", "type": "landmark", "distance": "5 min drive"}, {"name": "DIFC", "type": "business", "distance": "3 min drive"}, {"name": "Dubai Water Canal", "type": "landmark", "distance": "2 min walk"}],
    imageGallery: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&h=800&fit=crop", "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&h=800&fit=crop"],
    faqs: [{"question": "What makes this branded?", "answer": "Jacob & Co designed all interiors, lobby, and amenity spaces with signature luxury aesthetic."}, {"question": "Golden Visa eligible?", "answer": "Yes, all units exceed AED 2M and qualify for 10-year Golden Visa."}],
    ctaHeadline: 'Own a Piece of History',
    metaTitle: 'Burj Binghatti Jacob & Co | Business Bay | Binayah',
    publishStatus: 'Published',
  },
  {
    name: 'Palm Jebel Ali Villas by Nakheel',
    slug: 'palm-jebel-ali-villas',
    status: 'New Launch',
    propertyType: 'Villa',
    developerName: 'Nakheel',
    community: 'Palm Jebel Ali',
    startingPrice: 18000000,
    priceRange: 'AED 18M - AED 70M+',
    completionDate: new Date('2029-12-31'),
    constructionStatus: 'Infrastructure Phase',
    downPayment: '10%',
    paymentPlanSummary: '90/10 Payment Plan',
    unitTypes: ["5 Bedrooms", "6 Bedrooms", "7 Bedrooms", "Mansion"],
    unitSizeMin: 7000,
    unitSizeMax: 30000,
    totalUnits: 80,
    shortOverview: 'Ultra-exclusive beachfront mansions on Palm Jebel Ali — Dubai\'s next iconic waterfront destination.',
    fullDescription: 'These bespoke beachfront mansions offer private beach, infinity pools, boat berths. Plots exceeding 15,000 sqft with up to 30,000 sqft built-up — among the largest in the UAE.',
    targetBuyers: ["UHNW Individuals", "Royal Families"],
    investmentHighlights: ["Rare beachfront plots", "2x size of Palm Jumeirah", "Only 80 villas", "Generational wealth asset"],
    keyHighlights: ["Private beach per villa", "Personal boat berth", "Plots from 15,000 sqft", "Bespoke architecture", "Direct sea access"],
    amenities: ["Private Beach", "Boat Berth", "Infinity Pool", "Private Gym", "Staff Quarters", "Smart Home", "24/7 Security", "Beach Club"],
    imageGallery: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&h=800&fit=crop", "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&h=800&fit=crop"],
    faqs: [{"question": "Can I customize the design?", "answer": "Yes, bespoke \u2014 select your architect from Nakheel's approved list."}, {"question": "Good investment?", "answer": "Palm Jumeirah villas appreciated 200%+. Palm Jebel Ali expected to follow."}],
    ctaHeadline: 'The Rarest Address in Dubai',
    metaTitle: 'Palm Jebel Ali Villas | Mansions from AED 18M | Binayah',
    publishStatus: 'Published',
  },
  {
    name: 'Sobha One',
    slug: 'sobha-one',
    status: 'Off-Plan',
    propertyType: 'Apartment',
    developerName: 'Sobha Realty',
    community: 'Sobha Hartland',
    startingPrice: 1600000,
    priceRange: 'AED 1.6M - AED 12M',
    completionDate: new Date('2027-12-31'),
    constructionStatus: 'Under Construction — 35% Complete',
    downPayment: '20%',
    paymentPlanSummary: '80/20 Payment Plan',
    unitTypes: ["1 Bedroom", "1.5 Bedrooms", "2 Bedrooms", "3 Bedrooms"],
    unitSizeMin: 680,
    unitSizeMax: 3200,
    totalUnits: 1400,
    shortOverview: 'Premium twin-tower residences by Sobha Realty in Hartland, known for exceptional build quality.',
    fullDescription: 'Twin 65-storey towers on Dubai Creek banks with wildlife sanctuary views, Downtown skyline, and Meydan racecourse panoramas. Lagoon pool, private cinema, co-working spaces.',
    targetBuyers: ["End Users", "Investors", "Couples", "Professionals"],
    investmentHighlights: ["Sobha premium quality", "Creek views", "7% estimated yield", "Below Palm pricing"],
    keyHighlights: ["Twin 65-storey towers", "Lagoon-style pool", "Creek & wildlife views", "Sobha quality finishes", "Private cinema", "Green community"],
    amenities: ["Lagoon Pool", "Gymnasium", "Private Cinema", "Co-working", "Kids Area", "Jogging Track", "Cycling Path", "Retail", "Gardens", "BBQ", "Concierge"],
    nearbyAttractions: [{"name": "Ras Al Khor Sanctuary", "type": "nature", "distance": "3 min drive"}, {"name": "Meydan Racecourse", "type": "entertainment", "distance": "5 min drive"}, {"name": "Downtown Dubai", "type": "landmark", "distance": "8 min drive"}],
    imageGallery: ["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&h=800&fit=crop", "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&h=800&fit=crop"],
    faqs: [{"question": "What is Sobha Hartland?", "answer": "8-million sqft master-planned community by Sobha in MBR City with apartments, villas, schools, retail."}, {"question": "What makes Sobha special?", "answer": "Sobha handles everything in-house \u2014 design to finishing \u2014 ensuring exceptional quality."}],
    ctaHeadline: 'Live in Sobha One',
    metaTitle: 'Sobha One | Sobha Hartland Apartments | Binayah',
    publishStatus: 'Published',
  },
  {
    name: 'Emaar The Valley Phase 3',
    slug: 'emaar-the-valley-phase-3',
    status: 'New Launch',
    propertyType: 'Townhouse',
    developerName: 'Emaar Properties',
    community: 'The Valley',
    startingPrice: 1400000,
    priceRange: 'AED 1.4M - AED 3.2M',
    completionDate: new Date('2027-09-30'),
    constructionStatus: 'Excavation Complete',
    downPayment: '10%',
    paymentPlanSummary: '80/20 Payment Plan',
    unitTypes: ["3 Bedrooms", "4 Bedrooms"],
    unitSizeMin: 1800,
    unitSizeMax: 2800,
    totalUnits: 500,
    shortOverview: 'Affordable Emaar townhouses in The Valley — Dubai\'s fastest-growing family community with town centre, sports fields, and schools.',
    fullDescription: 'Phase 3 brings new designs to this thriving community. Town centre, sports complex, parks, school district. Phase 1 buyers saw 40%+ appreciation.',
    targetBuyers: ["Families", "First-Time Buyers", "End Users"],
    investmentHighlights: ["Emaar brand", "Affordable entry", "Phase 1 up 40%", "High family demand", "Infrastructure complete"],
    keyHighlights: ["New townhouse designs", "Town centre", "Sports complex", "Parks & green spaces", "School district", "Emaar warranty"],
    amenities: ["Community Pool", "Sports Complex", "Skate Park", "BMX Track", "Kids Areas", "Town Centre", "Retail & Dining", "Jogging Tracks", "Mosque", "Medical Centre"],
    imageGallery: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&h=800&fit=crop", "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&h=800&fit=crop"],
    faqs: [{"question": "How does it compare?", "answer": "Emaar quality at more accessible prices than Dubai Hills or Arabian Ranches. Phase 1 buyers saw 40%+ appreciation."}, {"question": "Service charge?", "answer": "Estimated AED 3-4/sqft \u2014 very competitive for an Emaar community."}],
    ctaHeadline: 'Emaar Family Living from AED 1.4M',
    metaTitle: 'Emaar The Valley Phase 3 | Townhouses | Binayah',
    publishStatus: 'Published',
  },
  {
    name: 'DAMAC Sun City',
    slug: 'damac-sun-city',
    status: 'Off-Plan',
    propertyType: 'Villa',
    developerName: 'DAMAC Properties',
    community: 'Dubailand',
    startingPrice: 2500000,
    priceRange: 'AED 2.5M - AED 8M',
    completionDate: new Date('2028-06-30'),
    constructionStatus: 'Under Construction — 20% Complete',
    downPayment: '20%',
    paymentPlanSummary: '60/40 Payment Plan',
    unitTypes: ["4 Bedrooms", "5 Bedrooms", "6 Bedrooms"],
    unitSizeMin: 3500,
    unitSizeMax: 7000,
    totalUnits: 1000,
    shortOverview: 'Tropical resort-style villas by DAMAC with crystal lagoons, lazy rivers, and themed gardens.',
    fullDescription: 'DAMAC Sun City brings tropical paradise to Dubai. Crystal lagoons, lazy rivers, themed neighborhoods — resort-style living year-round with water park and beach club.',
    targetBuyers: ["Families", "End Users", "Investors"],
    investmentHighlights: ["DAMAC brand", "Crystal lagoon amenities", "Affordable villa entry", "High demand area"],
    keyHighlights: ["Crystal lagoon beaches", "Lazy river", "Tropical gardens", "Water park & beach club", "Smart villas", "Gated & secure"],
    amenities: ["Crystal Lagoon", "Lazy River", "Water Park", "Beach Club", "Gymnasium", "Kids Zones", "Sports Courts", "Retail Village", "Restaurants", "Spa", "Dog Park"],
    imageGallery: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&h=800&fit=crop", "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&h=800&fit=crop"],
    faqs: [{"question": "What is a crystal lagoon?", "answer": "Man-made beach with crystal-clear, temperature-controlled water for swimming, kayaking, paddleboarding."}, {"question": "Post-handover?", "answer": "Yes, DAMAC offers 3-year post-handover at 0% interest on select units."}],
    ctaHeadline: 'Tropical Villa Living',
    metaTitle: 'DAMAC Sun City | Tropical Villas | Binayah',
    publishStatus: 'Published',
  },
  {
    name: 'Downtown Views III by Emaar',
    slug: 'downtown-views-3-emaar',
    status: 'Off-Plan',
    propertyType: 'Apartment',
    developerName: 'Emaar Properties',
    community: 'Downtown Dubai',
    startingPrice: 2200000,
    priceRange: 'AED 2.2M - AED 9M',
    completionDate: new Date('2027-03-31'),
    constructionStatus: 'Under Construction — 55% Complete',
    downPayment: '10%',
    paymentPlanSummary: '70/30 Payment Plan',
    unitTypes: ["1 Bedroom", "2 Bedrooms", "3 Bedrooms", "4 Bedrooms"],
    unitSizeMin: 700,
    unitSizeMax: 3500,
    totalUnits: 350,
    availabilityStatus: 'Limited',
    shortOverview: 'Premium Emaar apartments in Downtown Dubai with iconic Burj Khalifa and fountain views.',
    fullDescription: 'On Mohammed bin Rashid Boulevard with unobstructed Burj Khalifa and Dubai Fountain views. Direct access to Dubai Mall, Opera District, Souk Al Bahar — the most coveted address in the Middle East.',
    targetBuyers: ["End Users", "Investors", "Luxury Buyers", "Professionals"],
    investmentHighlights: ["Emaar Downtown address", "Burj Khalifa views", "Walking to Dubai Mall", "Premium rental demand", "Golden Visa eligible"],
    keyHighlights: ["Burj Khalifa & fountain views", "Walking to Dubai Mall", "MBR Boulevard address", "Emaar finishes", "Smart home ready", "Residents' pool"],
    amenities: ["Infinity Pool", "Gymnasium", "Residents' Lounge", "Kids Area", "BBQ Terrace", "Landscaped Podium", "Retail", "Concierge", "Valet", "24/7 Security"],
    nearbyAttractions: [{"name": "Burj Khalifa", "type": "landmark", "distance": "5 min walk"}, {"name": "Dubai Mall", "type": "mall", "distance": "7 min walk"}, {"name": "Dubai Opera", "type": "entertainment", "distance": "8 min walk"}, {"name": "DIFC", "type": "business", "distance": "5 min drive"}],
    imageGallery: ["https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&h=800&fit=crop", "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&h=800&fit=crop", "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&h=800&fit=crop"],
    faqs: [{"question": "Which units have Burj Khalifa views?", "answer": "All 2BR+ north-east facing units have direct Burj Khalifa and fountain views."}, {"question": "Fountain view premium?", "answer": "Approximately 15-20% premium over city-view units."}, {"question": "Good investment?", "answer": "Downtown delivers 5-6% yields with strong capital appreciation. Most liquid market in Dubai."}],
    ctaHeadline: 'Own the View of a Lifetime',
    metaTitle: 'Downtown Views III | Emaar Downtown Dubai | Binayah',
    publishStatus: 'Published',
  },
  {
    name: 'Binghatti Aurora',
    slug: 'binghatti-aurora-jvc',
    status: 'Off-Plan',
    propertyType: 'Apartment',
    developerName: 'Binghatti',
    community: 'Jumeirah Village Circle',
    startingPrice: 580000,
    priceRange: 'AED 580K - AED 1.5M',
    completionDate: new Date('2026-09-30'),
    constructionStatus: 'Under Construction — 60% Complete',
    downPayment: '10%',
    paymentPlanSummary: '60/40 Payment Plan',
    unitTypes: ["Studio", "1 Bedroom", "2 Bedrooms"],
    unitSizeMin: 350,
    unitSizeMax: 1200,
    totalUnits: 250,
    shortOverview: 'Affordable luxury in JVC from AED 580K — Dubai\'s highest rental yield area at 8-9%.',
    fullDescription: 'Contemporary design and smart living in JVC. Perfect for young professionals and investors. JVC ranks #1 in Dubai for rental yields.',
    targetBuyers: ["Investors", "First-Time Buyers", "Young Professionals"],
    investmentHighlights: ["Highest yields (8-9%)", "Lowest entry point", "Strong tenant demand", "Central location"],
    keyHighlights: ["Premium Binghatti design", "Smart home features", "Rooftop infinity pool", "Co-working lounge", "Pet-friendly", "Below AED 600K entry"],
    amenities: ["Rooftop Pool", "Gymnasium", "Co-working", "Kids Area", "BBQ Deck", "Retail", "Covered Parking", "24/7 Security"],
    nearbyAttractions: [{"name": "Circle Mall", "type": "mall", "distance": "5 min drive"}, {"name": "Dubai Marina", "type": "landmark", "distance": "12 min drive"}, {"name": "Mall of Emirates", "type": "mall", "distance": "10 min drive"}],
    imageGallery: ["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&h=800&fit=crop", "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&h=800&fit=crop"],
    faqs: [{"question": "What rental yield?", "answer": "JVC studios achieve 8-9% gross \u2014 the highest in Dubai."}, {"question": "Is JVC well-connected?", "answer": "Direct access to Al Khail Road. 12 mins to Marina, 15 mins to Downtown."}],
    ctaHeadline: 'Invest from AED 580K',
    metaTitle: 'Binghatti Aurora JVC | Studios from AED 580K | Binayah',
    publishStatus: 'Published',
  },
  {
    name: 'Dubai Hills Grove by Emaar',
    slug: 'dubai-hills-grove-emaar',
    status: 'Off-Plan',
    propertyType: 'Apartment',
    developerName: 'Emaar Properties',
    community: 'Dubai Hills Estate',
    startingPrice: 1300000,
    priceRange: 'AED 1.3M - AED 4.5M',
    completionDate: new Date('2027-06-30'),
    constructionStatus: 'Under Construction — 40% Complete',
    downPayment: '10%',
    paymentPlanSummary: '80/20 Payment Plan',
    unitTypes: ["1 Bedroom", "2 Bedrooms", "3 Bedrooms"],
    unitSizeMin: 650,
    unitSizeMax: 2400,
    totalUnits: 480,
    shortOverview: 'Green community apartments by Emaar with golf course views, walking trails, and Dubai Hills Mall access.',
    fullDescription: 'Set within Dubai Hills Estate with direct access to the 18-hole championship golf course, extensive parks, cycling trails, and Dubai Hills Mall.',
    targetBuyers: ["End Users", "Families", "Investors", "Golf Enthusiasts"],
    investmentHighlights: ["Emaar Dubai Hills", "Golf course views", "Strong appreciation", "Family demand", "Near Dubai Hills Mall"],
    keyHighlights: ["Golf course views", "Dubai Hills Mall access", "Parks & running trails", "Emaar quality", "Community pool & gym", "Close to schools"],
    amenities: ["Swimming Pool", "Gymnasium", "Kids Area", "Jogging Tracks", "Cycling Paths", "BBQ Areas", "Retail", "Gardens", "24/7 Security", "Covered Parking"],
    nearbyAttractions: [{"name": "Dubai Hills Mall", "type": "mall", "distance": "5 min drive"}, {"name": "Dubai Hills Golf Club", "type": "sport", "distance": "3 min drive"}, {"name": "Dubai Hills Park", "type": "park", "distance": "2 min walk"}],
    imageGallery: ["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&h=800&fit=crop", "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&h=800&fit=crop", "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1200&h=800&fit=crop"],
    faqs: [{"question": "Good for families?", "answer": "Yes \u2014 multiple schools (GEMS, King's), parks, mall, safe gated community."}, {"question": "What views?", "answer": "Golf course, Dubai Hills Park, or city skyline depending on orientation."}],
    ctaHeadline: 'Green Living by Emaar',
    metaTitle: 'Dubai Hills Grove | Emaar Apartments | Binayah',
    publishStatus: 'Published',
  },
  {
    name: 'Rashid Yachts & Marina Residences',
    slug: 'rashid-yachts-marina-residences',
    status: 'Off-Plan',
    propertyType: 'Apartment',
    developerName: 'Emaar Properties',
    community: 'Port Rashid',
    startingPrice: 1900000,
    priceRange: 'AED 1.9M - AED 15M',
    completionDate: new Date('2028-12-31'),
    constructionStatus: 'Under Construction — 25% Complete',
    downPayment: '10%',
    paymentPlanSummary: '80/20 Payment Plan',
    unitTypes: ["1 Bedroom", "2 Bedrooms", "3 Bedrooms", "4 Bedrooms", "Penthouse"],
    unitSizeMin: 750,
    unitSizeMax: 5500,
    totalUnits: 600,
    shortOverview: 'Emaar\'s newest waterfront — superyacht marina, cruise terminal, and luxury residences at Port Rashid.',
    fullDescription: 'Emaar\'s transformation of historic Port Rashid: 430-berth superyacht marina, cruise terminal, 10km waterfront promenades, and world-class retail. Panoramic sea views with old Dubai\'s heritage nearby.',
    targetBuyers: ["End Users", "Investors", "Luxury Buyers", "Yacht Owners"],
    investmentHighlights: ["Emaar mega-development", "Superyacht marina", "Historic port transformation", "Rare sea-view supply", "Cruise tourism boost"],
    keyHighlights: ["Superyacht marina views", "10km waterfront", "International cruise terminal", "Heritage district nearby", "Emaar quality", "Direct marina access"],
    amenities: ["Infinity Pool", "Beach Club", "Marina Promenade", "Fine Dining", "Retail Boulevard", "Gymnasium", "Spa", "Kids Club", "Water Sports", "Yacht Club", "Concierge"],
    nearbyAttractions: [{"name": "Gold Souk", "type": "shopping", "distance": "5 min drive"}, {"name": "Dubai Museum", "type": "culture", "distance": "7 min drive"}, {"name": "Dubai Frame", "type": "landmark", "distance": "8 min drive"}, {"name": "DXB Airport", "type": "airport", "distance": "10 min drive"}],
    imageGallery: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&h=800&fit=crop", "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&h=800&fit=crop", "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&h=800&fit=crop"],
    faqs: [{"question": "Marina capacity?", "answer": "430 berths for yachts up to 100m."}, {"question": "Near old Dubai?", "answer": "Adjacent to Bur Dubai, Gold Souk, and historic creek."}],
    ctaHeadline: 'Dubai\'s New Waterfront',
    metaTitle: 'Rashid Yachts & Marina | Emaar Port Rashid | Binayah',
    publishStatus: 'Published',
  },
];

async function seed() {
  console.log("Connecting to MongoDB...");
  await mongoose.connect(MONGODB_URI);
  console.log("Connected!\n");

  const existing = await Project.countDocuments();
  if (existing > 0) {
    console.log(`Removing ${existing} existing projects...`);
    await Project.deleteMany({});
  }

  const result = await Project.insertMany(seedProjects);
  console.log(`✓ Seeded ${result.length} projects\n`);

  console.log("Projects:");
  console.log("─".repeat(80));
  result.forEach((p, i) => {
    const price = p.startingPrice ? `AED ${(p.startingPrice / 1_000_000).toFixed(1)}M+` : "TBD";
    console.log(`  ${i + 1}. ${p.name.padEnd(40)} ${(p.community || "").padEnd(25)} ${price}`);
  });
  console.log("─".repeat(80));

  await mongoose.disconnect();
  console.log("\n✓ Done! Run 'npm run dev' to see your site.");
}

seed().catch((err) => { console.error("Seed error:", err); process.exit(1); });
