// ── Source-city buyer pages ───────────────────────────────────────────────
// Powers /buying-property-in-dubai-from/[city]. These are deliberately NOT the
// nationality pages with the country swapped: the citizen guide covers who may
// own what and how it is taxed, while these cover the logistics of buying at a
// distance — flights, time zones, what needs a power of attorney, how funds
// actually route, and what an owner manages remotely. Each page links to its
// citizen guide rather than restating it.

import type { LocalizedText } from "./foreign-buyers";

export interface SourceCity {
  slug: string;
  city: string;
  country: string;
  flag: string;
  /** Matching ForeignBuyerProfile slug, for the cross-link. */
  citizenSlug: string;
  metaTitle: LocalizedText;
  metaDesc: LocalizedText;
  h1: LocalizedText;
  intro: LocalizedText;
  /** Buying without being there: flights, time zone, power of attorney. */
  remote: LocalizedText;
  /** Getting the money there. */
  money: LocalizedText;
  /** Owning and letting it from that city. */
  managing: LocalizedText;
  /** Display names; mapped to community slugs in the page template. */
  areas: string[];
}

export const SOURCE_CITIES: SourceCity[] = [
  {
    slug: "singapore",
    city: "Singapore",
    country: "Singapore",
    flag: "🇸🇬",
    citizenSlug: "singaporean-citizen",
    metaTitle: {
      en: "Buying Property in Dubai from Singapore | 2026 Buyer Guide",
      fr: "Acheter un bien à Dubaï depuis Singapour | Guide 2026",
      ru: "Покупка недвижимости в Дубае из Сингапура | Гид покупателя 2026",
      ar: "شراء عقار في دبي من سنغافورة | دليل المشتري 2026",
      zh: "从新加坡购买迪拜房产 | 2026 买家指南",
      vi: "Mua bất động sản Dubai từ Singapore | Hướng dẫn 2026",
      he: "רכישת נכס בדובאי מסינגפור | מדריך לרוכש 2026"
    },
    metaDesc: {
      en: "How to buy Dubai property from Singapore: remote purchase, SGD transfers, viewing trips, ABSD comparison and what a Singapore-based owner actually manages.",
      fr: "Comment acheter à Dubaï depuis Singapour : achat à distance, virements en SGD, voyages de visite, comparaison ABSD et ce qu'un propriétaire basé à Singapour gère réellement.",
      ru: "Как купить недвижимость в Дубае из Сингапура: удалённая сделка, переводы в SGD, смотровые поездки, сравнение с ABSD и что реально ведёт собственник из Сингапура.",
      ar: "كيف تشتري عقاراً في دبي من سنغافورة: الشراء عن بُعد، وتحويلات الدولار السنغافوري، ورحلات المعاينة، ومقارنة ABSD، وما يديره المالك المقيم في سنغافورة فعلياً.",
      zh: "如何从新加坡购买迪拜房产：远程成交、新元汇款、看房行程、ABSD 对比，以及新加坡业主实际需要打理什么。",
      vi: "Cách mua bất động sản Dubai từ Singapore: giao dịch từ xa, chuyển tiền SGD, chuyến đi xem nhà, so sánh ABSD và những gì một chủ sở hữu ở Singapore thực sự phải quản lý.",
      he: "איך לרכוש נכס בדובאי מסינגפור: רכישה מרחוק, העברות ב-SGD, נסיעות צפייה, השוואת ABSD ומה בעלים מסינגפור באמת מנהל."
    },
    h1: {
      en: "Buying property in Dubai from Singapore",
      fr: "Acheter un bien à Dubaï depuis Singapour",
      ru: "Покупка недвижимости в Дубае из Сингапура",
      ar: "شراء عقار في دبي من سنغافورة",
      zh: "从新加坡购买迪拜房产",
      vi: "Mua bất động sản Dubai từ Singapore",
      he: "רכישת נכס בדובאי מסינגפור"
    },
    intro: {
      en: "This page is about the logistics of buying from Singapore rather than the legal position of a Singaporean buyer — the ownership rules, ABSD arithmetic and tax treatment live on the citizen guide, which is linked below. Here the question is narrower and more practical: how does a purchase actually run when you are 5,900 km away, what has to happen in person, and what can be done entirely from a desk in Singapore?",
      fr: "Cette page traite de la logistique d'un achat depuis Singapour et non de la situation juridique d'un acheteur singapourien — les règles de propriété, l'arithmétique de l'ABSD et le traitement fiscal figurent dans le guide par nationalité, lié ci-dessous. Ici la question est plus étroite et plus pratique : comment une acquisition se déroule-t-elle réellement à 5 900 km de distance, que faut-il faire en personne, et que peut-on traiter entièrement depuis un bureau à Singapour ?",
      ru: "Эта страница о логистике покупки из Сингапура, а не о правовом положении сингапурского покупателя: правила владения, арифметика ABSD и налоговый режим — в гиде по гражданству, ссылка ниже. Здесь вопрос уже и практичнее: как реально проходит сделка, когда вы за 5 900 км, что нужно делать лично, а что можно сделать целиком из офиса в Сингапуре?",
      ar: "تتناول هذه الصفحة الجوانب اللوجستية للشراء من سنغافورة لا الوضع القانوني للمشتري السنغافوري — فقواعد التملك وحساب ABSD والمعاملة الضريبية موجودة في دليل الجنسية، والرابط أدناه. أما هنا فالسؤال أضيق وأكثر عملية: كيف تجري الصفقة فعلياً وأنت على بُعد 5900 كم، وما الذي يجب أن يتم حضورياً، وما الذي يمكن إنجازه بالكامل من مكتب في سنغافورة؟",
      zh: "本页讲的是从新加坡购房的操作流程，而非新加坡买家的法律地位——产权规则、ABSD 算术与税务处理都在国籍指南中，链接见下方。这里的问题更具体也更实际：当您远在 5,900 公里之外时，一笔交易究竟如何推进，哪些环节必须亲自到场，哪些可以完全在新加坡的办公桌前完成？",
      vi: "Trang này nói về khâu hậu cần khi mua từ Singapore chứ không phải vị thế pháp lý của người mua Singapore — quy định sở hữu, phép tính ABSD và cách xử lý thuế nằm ở hướng dẫn theo quốc tịch, có liên kết bên dưới. Ở đây câu hỏi hẹp hơn và thực tế hơn: một giao dịch thực sự diễn ra thế nào khi bạn ở cách 5.900 km, việc gì bắt buộc phải có mặt, và việc gì có thể làm trọn vẹn từ bàn làm việc ở Singapore?",
      he: "העמוד הזה עוסק בלוגיסטיקה של רכישה מסינגפור ולא במעמד המשפטי של רוכש סינגפורי — כללי הבעלות, חשבון ה-ABSD והטיפול המיסויי נמצאים במדריך לפי אזרחות, המקושר למטה. כאן השאלה צרה ומעשית יותר: איך עסקה באמת מתנהלת כשאתם במרחק 5,900 ק\"מ, מה חייב להיעשות פנים אל פנים, ומה אפשר לבצע כולו משולחן בסינגפור?"
    },
    remote: {
      en: "A Dubai purchase can be completed without you boarding a plane. Title transfer at the Dubai Land Department can be handled by an attorney acting under a power of attorney notarised in Singapore and attested for UAE use, and off-plan bookings with developers are routinely done remotely — reservation form, KYC pack, and payments by transfer. Most Singaporean buyers still fly once, usually to view a shortlist rather than to sign, and Singapore Airlines and Emirates both run daily non-stops of about 7 hours. Dubai is 4 hours behind Singapore, so a morning call in Dubai is your early evening, which makes the handover and snagging stage easy to supervise from home.",
      fr: "Une acquisition à Dubaï peut se conclure sans que vous preniez l'avion. Le transfert de titre au Dubai Land Department peut être assuré par un avocat agissant en vertu d'une procuration notariée à Singapour et légalisée pour usage aux Émirats, et les réservations sur plan auprès des promoteurs se font couramment à distance — formulaire de réservation, dossier KYC et paiements par virement. La plupart des acheteurs singapouriens font tout de même un déplacement, généralement pour visiter une liste restreinte plutôt que pour signer. Singapore Airlines et Emirates assurent des vols directs quotidiens d'environ 7 heures. Dubaï a 4 heures de retard sur Singapour : un appel matinal à Dubaï correspond à votre début de soirée, ce qui rend la phase de livraison et de réception facile à superviser depuis chez vous.",
      ru: "Сделку в Дубае можно завершить, не садясь в самолёт. Переход права в Dubai Land Department может провести представитель по доверенности, нотариально удостоверенной в Сингапуре и легализованной для использования в UAE, а бронирования у застройщиков на этапе строительства обычно делаются удалённо: форма брони, пакет KYC и платежи переводом. Большинство сингапурских покупателей всё же прилетают один раз — как правило, посмотреть шорт-лист, а не подписать. Singapore Airlines и Emirates выполняют ежедневные прямые рейсы около 7 часов. Дубай на 4 часа позади Сингапура, поэтому утренний звонок в Дубае — ваш ранний вечер, и этап передачи и приёмки легко контролировать из дома.",
      ar: "يمكن إتمام الشراء في دبي دون أن تستقل طائرة. فنقل الملكية لدى دائرة الأراضي والأملاك يمكن أن يتولاه محامٍ بموجب وكالة موثّقة في سنغافورة ومصدّقة للاستخدام في الإمارات، وحجوزات الخارطة لدى المطوّرين تتم عن بُعد بشكل معتاد — استمارة حجز، وملف «اعرف عميلك»، ودفعات بالتحويل. ومع ذلك يسافر معظم المشترين السنغافوريين مرة واحدة، غالباً لمعاينة قائمة مختصرة لا للتوقيع، وتُسيّر Singapore Airlines وEmirates رحلات مباشرة يومية مدتها نحو 7 ساعات. ودبي تتأخر 4 ساعات عن سنغافورة، فمكالمة صباحية في دبي هي مساؤك المبكر، ما يجعل مرحلة التسليم وفحص العيوب سهلة الإشراف من المنزل.",
      zh: "迪拜的购房交易无需您亲自搭机即可完成。迪拜土地局的产权过户可由律师依据在新加坡公证、并经认证供阿联酋使用的授权书代为办理；向开发商预订期房通常也在远程完成——预订表、KYC 材料包、以及电汇付款。多数新加坡买家仍会飞一趟，通常是看候选清单而非签约；新加坡航空与阿联酋航空均有每日直飞，航程约 7 小时。迪拜比新加坡晚 4 小时，因此迪拜的上午通话正是您的傍晚，这让交房与验房阶段很容易在家中监督。",
      vi: "Một giao dịch ở Dubai có thể hoàn tất mà bạn không cần lên máy bay. Việc sang tên tại Dubai Land Department có thể do luật sư thực hiện theo giấy ủy quyền được công chứng tại Singapore và hợp pháp hóa để dùng tại UAE, còn việc đặt chỗ căn hình thành trong tương lai với chủ đầu tư thường được làm từ xa — phiếu đặt chỗ, bộ hồ sơ KYC và thanh toán bằng chuyển khoản. Phần lớn người mua Singapore vẫn bay một lần, thường là để xem danh sách rút gọn chứ không phải để ký. Singapore Airlines và Emirates đều có chuyến thẳng hằng ngày khoảng 7 giờ. Dubai chậm hơn Singapore 4 giờ, nên một cuộc gọi buổi sáng ở Dubai là chiều tối của bạn, khiến giai đoạn bàn giao và nghiệm thu dễ giám sát từ nhà.",
      he: "אפשר להשלים רכישה בדובאי בלי לעלות למטוס. העברת הבעלות ב-Dubai Land Department יכולה להתבצע על ידי עורך דין הפועל מכוח ייפוי כוח שאומת בסינגפור ואושר לשימוש באיחוד, והזמנות על הנייר מול יזמים נעשות באופן שגרתי מרחוק — טופס הזמנה, תיק KYC ותשלומים בהעברה. עם זאת רוב הרוכשים הסינגפורים עדיין טסים פעם אחת, לרוב כדי לראות רשימה מצומצמת ולא כדי לחתום. Singapore Airlines ו-Emirates מפעילות טיסות ישירות יומיות של כ-7 שעות. דובאי מאחורי סינגפור ב-4 שעות, ולכן שיחה בבוקר בדובאי היא הערב המוקדם שלכם, מה שהופך את שלב המסירה ובדיקת הליקויים לקל לפיקוח מהבית."
    },
    money: {
      en: "Singapore has no exchange control and the SGD is fully convertible, so funding is a banking exercise, not a regulatory one — there is no approval to obtain and no transfer cap to work around. Prices are quoted and settled in dirhams, which are pegged to the US dollar, so your SGD converts once and the amount does not drift while the transaction runs. Two practical points. Ask your bank for the all-in rate including spread rather than the headline rate; on a property-sized transfer the spread is real money, and it is the single largest avoidable cost in the whole process. Second, UAE anti-money-laundering rules require documented source of funds before completion, and a RERA-registered brokerage must run that check on every buyer, so have CPF statements, employment income records or company accounts ready at the start rather than at the deadline.",
      fr: "Singapour n'a pas de contrôle des changes et le SGD est pleinement convertible : le financement relève de la banque, pas de la réglementation — aucune autorisation à obtenir, aucun plafond à contourner. Les prix sont libellés et réglés en dirhams, arrimés au dollar américain : vos SGD sont convertis une fois et le montant ne dérive pas pendant le déroulement de l'opération. Deux points pratiques. Demandez à votre banque le taux tout compris, spread inclus, plutôt que le taux affiché ; sur un virement de la taille d'un achat immobilier, le spread représente de l'argent réel et constitue le principal coût évitable de tout le processus. Ensuite, les règles émiriennes anti-blanchiment exigent une origine des fonds documentée avant la finalisation, et une agence enregistrée à la RERA doit mener ce contrôle sur chaque acquéreur : préparez relevés CPF, justificatifs de revenus ou comptes de société dès le départ.",
      ru: "В Сингапуре нет валютного контроля, а SGD полностью конвертируем, поэтому финансирование — банковская, а не регуляторная задача: разрешений получать не нужно, лимитов обходить тоже. Цены назначаются и оплачиваются в дирхамах, привязанных к доллару США, поэтому ваш SGD конвертируется один раз, и сумма не смещается, пока идёт сделка. Два практических момента. Запрашивайте у банка итоговый курс со спредом, а не заявленный: на переводе размером с покупку недвижимости спред — это реальные деньги и крупнейшая устранимая статья расходов во всём процессе. Второе: правила UAE по противодействию отмыванию требуют подтверждения происхождения средств до завершения, и брокер с лицензией RERA обязан провести эту проверку по каждому покупателю, поэтому готовьте выписки CPF, документы о доходах или отчётность компании заранее.",
      ar: "سنغافورة بلا رقابة صرف، والدولار السنغافوري قابل للتحويل بالكامل، فالتمويل مسألة مصرفية لا تنظيمية — لا إذن يجب الحصول عليه ولا سقف تحويل يجب الالتفاف حوله. وتُسعَّر الأسعار وتُسوَّى بالدرهم المربوط بالدولار الأمريكي، فيتحوّل الدولار السنغافوري مرة واحدة ولا ينحرف المبلغ أثناء سير الصفقة. ونقطتان عمليتان. اطلب من مصرفك السعر الشامل متضمناً الفارق لا السعر المعلن؛ ففي تحويل بحجم شراء عقار يكون الفارق مالاً حقيقياً، وهو أكبر تكلفة يمكن تفاديها في العملية كلها. والثانية أن قواعد مكافحة غسل الأموال في الإمارات تشترط إثبات مصدر الأموال قبل الإتمام، وأي وساطة مسجَّلة لدى RERA ملزَمة بذلك الفحص لكل مشترٍ، فجهّز كشوف CPF أو سجلات دخل العمل أو حسابات الشركة منذ البداية لا عند الموعد النهائي.",
      zh: "新加坡没有外汇管制，新元完全可自由兑换，因此筹资是一件银行业务而非监管难题——无需取得批准，也没有需要绕开的汇款上限。价格以迪拉姆报价并结算，而迪拉姆与美元挂钩，因此您的新元只兑换一次，交易进行期间金额不会漂移。两点实务提示。请向银行索取含点差的全包汇率，而非名义汇率；在一笔房产规模的汇款上，点差是实打实的钱，也是整个流程中最大的一项可避免成本。其二，阿联酋反洗钱规则要求在成交前提供资金来源证明，持有 RERA 牌照的中介必须对每位买家执行该审查，因此请在一开始就备好公积金对账单、雇佣收入记录或公司账目。",
      vi: "Singapore không có kiểm soát ngoại hối và SGD hoàn toàn chuyển đổi được, nên việc thu xếp tiền là chuyện ngân hàng chứ không phải thủ tục — không cần xin phép và không có trần chuyển tiền phải lách. Giá được niêm yết và thanh toán bằng dirham, vốn neo theo đô la Mỹ, nên SGD của bạn chỉ quy đổi một lần và số tiền không trôi trong lúc giao dịch diễn ra. Hai điểm thực tế. Hãy hỏi ngân hàng tỷ giá trọn gói đã gồm chênh lệch thay vì tỷ giá niêm yết; với khoản chuyển cỡ mua nhà, chênh lệch là tiền thật và là khoản chi phí tránh được lớn nhất trong cả quy trình. Thứ hai, quy định phòng chống rửa tiền của UAE yêu cầu chứng minh nguồn tiền trước khi hoàn tất, và sàn có giấy phép RERA phải kiểm tra điều đó với mọi người mua, nên hãy chuẩn bị sao kê CPF, hồ sơ thu nhập hoặc báo cáo công ty ngay từ đầu.",
      he: "בסינגפור אין פיקוח על מטבע חוץ וה-SGD ניתן להמרה מלאה, ולכן המימון הוא עניין בנקאי ולא רגולטורי — אין אישור להשיג ואין תקרת העברה לעקוף. המחירים נקובים ומשולמים בדירהם, הצמוד לדולר האמריקאי, כך שה-SGD שלכם מומר פעם אחת והסכום אינו נודד בזמן שהעסקה מתנהלת. שתי נקודות מעשיות. בקשו מהבנק את השער הכולל כולל המרווח ולא את השער המוצג; בהעברה בסדר גודל של רכישת נכס המרווח הוא כסף אמיתי, והוא ההוצאה הגדולה ביותר שניתן להימנע ממנה בכל התהליך. שנית, כללי איסור הלבנת ההון באיחוד דורשים הוכחת מקור כספים לפני ההשלמה, ותיווך רשום ב-RERA חייב לבצע בדיקה זו על כל רוכש, אז הכינו דוחות CPF, רישומי הכנסה מעבודה או דוחות חברה כבר בהתחלה."
    },
    managing: {
      en: "Running a Dubai apartment from Singapore is the part buyers underestimate, and it is more routine than it sounds. A managed let means the agent handles tenant sourcing, the Ejari tenancy registration, rent collection and the annual service-charge invoice, and remits net rent to your account. Rent in Dubai is increasingly collected monthly rather than in the traditional one or two cheques, which smooths the cash flow you actually receive. The recurring costs to model are the service charge, set per square foot by the building, and a municipality housing fee on rented homes — neither is a tax on the asset, and there is no annual property tax. Budget a vacancy allowance too: gross yields of roughly 5-8% assume the unit is let, and the honest net depends on how many weeks a year it is not.",
      fr: "Gérer un appartement dubaïote depuis Singapour est la partie que les acheteurs sous-estiment, et elle est plus routinière qu'il n'y paraît. Une location gérée signifie que l'agent s'occupe de la recherche de locataire, de l'enregistrement du bail Ejari, de l'encaissement des loyers et de la facture annuelle de charges, puis vous reverse le loyer net. Le loyer à Dubaï est de plus en plus encaissé mensuellement plutôt qu'en un ou deux chèques comme autrefois, ce qui lisse la trésorerie que vous percevez réellement. Les coûts récurrents à modéliser sont les charges, fixées au pied carré par l'immeuble, et une redevance municipale de logement sur les biens loués — ni l'une ni l'autre n'est un impôt sur l'actif, et il n'existe pas de taxe foncière annuelle. Prévoyez aussi une provision pour vacance : des rendements bruts de 5-8% supposent le bien loué, et le net honnête dépend du nombre de semaines où il ne l'est pas.",
      ru: "Управление квартирой в Дубае из Сингапура — то, что покупатели недооценивают, хотя всё довольно рутинно. Управляемая аренда означает, что агент ведёт поиск арендатора, регистрацию договора Ejari, сбор аренды и годовой счёт за сервисные сборы, а чистую аренду переводит на ваш счёт. Аренда в Дубае всё чаще собирается ежемесячно, а не традиционными одним-двумя чеками, что сглаживает фактически получаемый денежный поток. Регулярные расходы для модели: сервисный сбор, устанавливаемый зданием за квадратный фут, и муниципальный жилищный сбор на сдаваемое жильё — ни то, ни другое не является налогом на актив, а ежегодного налога на недвижимость нет. Заложите и резерв на простой: валовая доходность примерно 5-8% предполагает, что объект сдан, а честная чистая зависит от того, сколько недель в году он пустует.",
      ar: "إدارة شقة في دبي من سنغافورة هي الجزء الذي يقلل المشترون من شأنه، وهي أكثر اعتيادية مما تبدو. فالتأجير المُدار يعني أن الوكيل يتولى إيجاد المستأجر، وتسجيل عقد الإيجار Ejari، وتحصيل الإيجار، وفاتورة رسوم الخدمات السنوية، ويحوّل صافي الإيجار إلى حسابك. ويُحصَّل الإيجار في دبي بصورة متزايدة شهرياً بدل الشيك أو الشيكين التقليديين، ما يجعل التدفق النقدي الذي تتلقاه أكثر انتظاماً. والتكاليف المتكررة التي ينبغي احتسابها هي رسوم الخدمات، التي يحددها المبنى للقدم المربعة، ورسم إسكان بلدي على المساكن المؤجَّرة — وليس أيٌّ منهما ضريبة على الأصل، ولا توجد ضريبة عقارية سنوية. واحسب مخصصاً للشغور أيضاً: فالعوائد الإجمالية البالغة نحو 5-8% تفترض أن الوحدة مؤجَّرة، والصافي الصادق يتوقف على عدد الأسابيع التي لا تكون فيها كذلك.",
      zh: "从新加坡打理一套迪拜公寓，是买家最容易低估的部分，实际上却比听起来更为常规。托管出租意味着中介负责寻找租客、办理 Ejari 租约登记、收取租金与处理年度物业费账单，并将净租金汇入您的账户。迪拜的租金越来越多按月收取，而非传统的一两张支票，这让您实际收到的现金流更为平滑。需要纳入测算的经常性支出是物业费（由楼盘按每平方英尺设定）以及出租房屋的市政住房费——两者都不是对资产征税，也没有年度房产税。另请预留空置准备：约 5-8% 的毛回报率以房屋已出租为前提，而诚实的净值取决于一年中有多少周未能出租。",
      vi: "Vận hành một căn hộ Dubai từ Singapore là phần người mua hay xem nhẹ, và thực tế nó thường nhật hơn vẻ ngoài. Cho thuê có quản lý nghĩa là đại lý lo tìm khách thuê, đăng ký hợp đồng Ejari, thu tiền thuê và hóa đơn phí dịch vụ hằng năm, rồi chuyển tiền thuê ròng vào tài khoản của bạn. Tiền thuê ở Dubai ngày càng được thu theo tháng thay vì một hai tờ séc như truyền thống, giúp dòng tiền bạn thực nhận đều đặn hơn. Các chi phí định kỳ cần tính là phí dịch vụ, do tòa nhà ấn định theo foot vuông, và phí nhà ở của thành phố với nhà cho thuê — cả hai đều không phải thuế đánh trên tài sản, và không có thuế bất động sản hằng năm. Hãy dự trù cả khoản trống nhà: lợi suất gộp khoảng 5-8% giả định căn hộ đang được thuê, còn con số ròng trung thực phụ thuộc vào số tuần trong năm nó bỏ trống.",
      he: "ניהול דירה בדובאי מסינגפור הוא החלק שרוכשים ממעיטים בערכו, והוא שגרתי יותר משנשמע. השכרה מנוהלת פירושה שהסוכן מטפל באיתור שוכר, ברישום חוזה ה-Ejari, בגביית שכר הדירה ובחשבונית דמי הניהול השנתית, ומעביר את שכר הדירה נטו לחשבונכם. שכר דירה בדובאי נגבה יותר ויותר חודשית ולא בשיק אחד או שניים כמקובל בעבר, מה שמחליק את תזרים המזומנים שאתם באמת מקבלים. העלויות השוטפות לתמחור הן דמי הניהול, שנקבעים לפי רגל רבועה על ידי הבניין, ואגרת דיור עירונית על דירות מושכרות — אף אחת מהן אינה מס על הנכס, ואין מס רכוש שנתי. תקצבו גם רזרבה לתקופות ריקות: תשואות ברוטו של כ-5-8% מניחות שהיחידה מושכרת, והנטו הכן תלוי בכמה שבועות בשנה היא אינה."
    },
    areas: ["Downtown Dubai", "Business Bay", "Dubai Marina", "DIFC", "Jumeirah Village Circle"],
  },
  {
    slug: "harare",
    city: "Harare",
    country: "Zimbabwe",
    flag: "🇿🇼",
    citizenSlug: "zimbabwean-citizen",
    metaTitle: {
      en: "Buying Property in Dubai from Harare | 2026 Buyer Guide",
      fr: "Acheter un bien à Dubaï depuis Harare | Guide 2026",
      ru: "Покупка недвижимости в Дубае из Хараре | Гид покупателя 2026",
      ar: "شراء عقار في دبي من هراري | دليل المشتري 2026",
      zh: "从哈拉雷购买迪拜房产 | 2026 买家指南",
      vi: "Mua bất động sản Dubai từ Harare | Hướng dẫn 2026",
      he: "רכישת נכס בדובאי מהרארה | מדריך לרוכש 2026"
    },
    metaDesc: {
      en: "How to buy Dubai property from Harare: routing funds from offshore accounts, exchange-control reality, remote purchase, payment plans and managing the asset from Zimbabwe.",
      fr: "Comment acheter à Dubaï depuis Harare : acheminer les fonds depuis des comptes offshore, réalité du contrôle des changes, achat à distance, échéanciers et gestion depuis le Zimbabwe.",
      ru: "Как купить недвижимость в Дубае из Хараре: маршрут средств с зарубежных счетов, реальность валютного контроля, удалённая сделка, рассрочки и управление активом из Зимбабве.",
      ar: "كيف تشتري عقاراً في دبي من هراري: توجيه الأموال من حسابات خارجية، وواقع رقابة الصرف، والشراء عن بُعد، وخطط السداد، وإدارة الأصل من زيمبابوي.",
      zh: "如何从哈拉雷购买迪拜房产：从境外账户安排资金、外汇管制的现实、远程成交、付款计划，以及从津巴布韦管理资产。",
      vi: "Cách mua bất động sản Dubai từ Harare: điều phối tiền từ tài khoản nước ngoài, thực tế kiểm soát ngoại hối, giao dịch từ xa, kế hoạch trả góp và quản lý tài sản từ Zimbabwe.",
      he: "איך לרכוש נכס בדובאי מהרארה: ניתוב כספים מחשבונות בחו\"ל, מציאות הפיקוח על מטבע חוץ, רכישה מרחוק, תוכניות תשלומים וניהול הנכס מזימבבואה."
    },
    h1: {
      en: "Buying property in Dubai from Harare",
      fr: "Acheter un bien à Dubaï depuis Harare",
      ru: "Покупка недвижимости в Дубае из Хараре",
      ar: "شراء عقار في دبي من هراري",
      zh: "从哈拉雷购买迪拜房产",
      vi: "Mua bất động sản Dubai từ Harare",
      he: "רכישת נכס בדובאי מהרארה"
    },
    intro: {
      en: "This page covers the mechanics of buying from Harare rather than the legal position of a Zimbabwean buyer — ownership rights, tax and the exchange-control background are set out on the citizen guide, linked below. What follows is the practical sequence: where the money realistically comes from, what can be done without travelling, and what a Harare-based owner manages once the keys exist. We will not advise on working around exchange control, and a RERA-registered brokerage runs KYC on every buyer regardless.",
      fr: "Cette page traite des mécanismes d'un achat depuis Harare et non de la situation juridique d'un acheteur zimbabwéen — les droits de propriété, la fiscalité et le contexte du contrôle des changes figurent dans le guide par nationalité, lié ci-dessous. Suit la séquence pratique : d'où viennent réellement les fonds, ce qui peut se faire sans voyager, et ce qu'un propriétaire basé à Harare gère une fois les clés remises. Nous ne conseillons pas sur les moyens de contourner le contrôle des changes, et une agence enregistrée à la RERA mène de toute façon un KYC sur chaque acquéreur.",
      ru: "Эта страница о механике покупки из Хараре, а не о правовом положении зимбабвийского покупателя: права собственности, налоги и контекст валютного контроля изложены в гиде по гражданству, ссылка ниже. Далее — практическая последовательность: откуда реально берутся деньги, что можно сделать без поездки и чем управляет собственник из Хараре после получения ключей. Мы не консультируем по обходу валютного контроля, и брокер с лицензией RERA проводит KYC по каждому покупателю в любом случае.",
      ar: "تتناول هذه الصفحة آليات الشراء من هراري لا الوضع القانوني للمشتري الزيمبابوي — فحقوق التملك والضرائب وخلفية رقابة الصرف مبيّنة في دليل الجنسية المرتبط أدناه. وما يلي هو التسلسل العملي: من أين تأتي الأموال واقعياً، وما الذي يمكن إنجازه دون سفر، وما الذي يديره مالك مقيم في هراري بعد تسلّم المفاتيح. ولا نقدّم مشورة بشأن الالتفاف على رقابة الصرف، وأي وساطة مسجَّلة لدى RERA تُجري «اعرف عميلك» على كل مشترٍ على أي حال.",
      zh: "本页讲的是从哈拉雷购房的操作机制，而非津巴布韦买家的法律地位——产权、税务与外汇管制背景已在国籍指南中说明，链接见下方。以下是实际的推进顺序：资金现实中从何而来、哪些环节无需出行即可完成，以及拿到钥匙之后，一位身在哈拉雷的业主需要打理什么。我们不会就规避外汇管制提供建议，而持有 RERA 牌照的中介无论如何都会对每位买家执行 KYC。",
      vi: "Trang này nói về cơ chế mua từ Harare chứ không phải vị thế pháp lý của người mua Zimbabwe — quyền sở hữu, thuế và bối cảnh kiểm soát ngoại hối được trình bày ở hướng dẫn theo quốc tịch, liên kết bên dưới. Phần tiếp theo là trình tự thực tế: tiền thực sự đến từ đâu, việc gì làm được mà không cần đi lại, và một chủ sở hữu ở Harare quản lý những gì sau khi có chìa khóa. Chúng tôi không tư vấn cách lách kiểm soát ngoại hối, và sàn có giấy phép RERA vẫn thực hiện KYC với mọi người mua.",
      he: "העמוד הזה עוסק במכניקה של רכישה מהרארה ולא במעמד המשפטי של רוכש זימבבואי — זכויות הבעלות, המיסוי ורקע הפיקוח על מטבע חוץ מפורטים במדריך לפי אזרחות, המקושר למטה. להלן הרצף המעשי: מהיכן מגיע הכסף באמת, מה אפשר לעשות בלי לנסוע, ומה מנהל בעלים מהרארה ברגע שיש מפתחות. איננו מייעצים כיצד לעקוף פיקוח על מטבע חוץ, ותיווך רשום ב-RERA מבצע KYC על כל רוכש בכל מקרה."
    },
    remote: {
      en: "There is no direct Harare-Dubai service, so most buyers connect through Johannesburg, Addis Ababa or Nairobi, putting the trip at roughly 8 hours in the air plus a layover. Dubai is 2 hours ahead of Harare, which is a small enough gap that a working day overlaps almost entirely — useful when a developer needs a same-day answer on a unit release. Travel is not required to complete: title transfer at the Dubai Land Department can be done by an attorney under a power of attorney notarised in Harare and attested for UAE use, and off-plan reservations are handled remotely with a booking form, a KYC pack and transfers. Given the funding constraints below, many Zimbabwean buyers deliberately visit once before committing, because a payment plan is much harder to unwind than a viewing trip is to make.",
      fr: "Il n'existe pas de liaison directe Harare-Dubaï : la plupart des acheteurs transitent par Johannesburg, Addis-Abeba ou Nairobi, ce qui porte le trajet à environ 8 heures de vol plus une escale. Dubaï a 2 heures d'avance sur Harare, un écart assez faible pour que la journée de travail se recouvre presque entièrement — utile quand un promoteur attend une réponse le jour même sur une mise en vente. Le déplacement n'est pas requis pour conclure : le transfert de titre au Dubai Land Department peut être assuré par un avocat en vertu d'une procuration notariée à Harare et légalisée pour usage aux Émirats, et les réservations sur plan se traitent à distance avec un formulaire, un dossier KYC et des virements. Compte tenu des contraintes de financement ci-dessous, beaucoup d'acheteurs zimbabwéens font délibérément un déplacement avant de s'engager, car défaire un échéancier est bien plus difficile qu'organiser une visite.",
      ru: "Прямого рейса Хараре — Дубай нет, поэтому большинство покупателей летят через Йоханнесбург, Аддис-Абебу или Найроби: примерно 8 часов в воздухе плюс пересадка. Дубай на 2 часа впереди Хараре — разрыв достаточно небольшой, чтобы рабочий день совпадал почти полностью, что полезно, когда застройщику нужен ответ по релизу юнита в тот же день. Поездка для завершения сделки не обязательна: переход права в Dubai Land Department может провести представитель по доверенности, удостоверенной в Хараре и легализованной для UAE, а бронирования на этапе строительства оформляются удалённо — форма брони, пакет KYC и переводы. Учитывая ограничения по финансированию ниже, многие зимбабвийские покупатели намеренно приезжают один раз до принятия обязательств, потому что расторгнуть рассрочку намного сложнее, чем съездить на просмотр.",
      ar: "لا توجد رحلة مباشرة بين هراري ودبي، فيعبر معظم المشترين عبر جوهانسبرغ أو أديس أبابا أو نيروبي، ما يجعل الرحلة نحو 8 ساعات طيران إضافةً إلى التوقف. ودبي تسبق هراري بساعتين، وهو فارق صغير بما يكفي ليتداخل يوم العمل بالكامل تقريباً، وهو أمر مفيد حين يحتاج المطوّر إلى رد في اليوم نفسه بشأن طرح وحدة. والسفر ليس شرطاً للإتمام: فنقل الملكية لدى دائرة الأراضي والأملاك يمكن أن يتولاه محامٍ بموجب وكالة موثّقة في هراري ومصدّقة للاستخدام في الإمارات، وتُدار حجوزات الخارطة عن بُعد باستمارة حجز وملف «اعرف عميلك» وتحويلات. وبالنظر إلى قيود التمويل أدناه، يزور كثير من المشترين الزيمبابويين عمداً مرة واحدة قبل الالتزام، لأن فك خطة السداد أصعب بكثير من القيام برحلة معاينة.",
      zh: "哈拉雷与迪拜之间没有直飞航班，多数买家经由约翰内斯堡、亚的斯亚贝巴或内罗毕中转，飞行时间约 8 小时另加经停。迪拜比哈拉雷早 2 小时，时差足够小，工作日几乎完全重叠——当开发商需要就某个单元的放售在当天给出答复时，这一点很有用。完成交易并不需要出行：迪拜土地局的过户可由律师依据在哈拉雷公证、并经认证供阿联酋使用的授权书办理；期房预订也可远程处理，只需预订表、KYC 材料包与汇款。鉴于下文的资金约束，许多津巴布韦买家会有意在作出承诺前先去一趟，因为解除一份付款计划远比安排一次看房行程困难得多。",
      vi: "Không có chuyến bay thẳng Harare - Dubai, nên phần lớn người mua nối chuyến qua Johannesburg, Addis Ababa hoặc Nairobi, tổng cộng khoảng 8 giờ bay cộng thời gian chờ. Dubai sớm hơn Harare 2 giờ, chênh lệch đủ nhỏ để ngày làm việc gần như trùng khớp hoàn toàn — hữu ích khi chủ đầu tư cần câu trả lời trong ngày về một đợt mở bán. Không bắt buộc phải đi lại để hoàn tất: việc sang tên tại Dubai Land Department có thể do luật sư thực hiện theo giấy ủy quyền công chứng tại Harare và hợp pháp hóa để dùng tại UAE, còn đặt chỗ căn hình thành trong tương lai được xử lý từ xa với phiếu đặt chỗ, bộ hồ sơ KYC và chuyển khoản. Với các ràng buộc tài chính nêu dưới đây, nhiều người mua Zimbabwe cố ý đi một chuyến trước khi cam kết, vì gỡ bỏ một kế hoạch thanh toán khó hơn nhiều so với thu xếp một chuyến đi xem nhà.",
      he: "אין טיסה ישירה בין הרארה לדובאי, ולכן רוב הרוכשים עוברים דרך יוהנסבורג, אדיס אבבה או ניירובי, מה שמעמיד את הנסיעה על כ-8 שעות טיסה בתוספת עצירת ביניים. דובאי מקדימה את הרארה בשעתיים, פער קטן מספיק כדי שיום העבודה יחפוף כמעט לגמרי — שימושי כשיזם צריך תשובה באותו יום על שחרור יחידה. נסיעה אינה נדרשת להשלמה: העברת בעלות ב-Dubai Land Department יכולה להתבצע על ידי עורך דין מכוח ייפוי כוח שאומת בהרארה ואושר לשימוש באיחוד, והזמנות על הנייר מטופלות מרחוק עם טופס הזמנה, תיק KYC והעברות. לאור מגבלות המימון שלהלן, רוכשים זימבבואים רבים מבקרים במכוון פעם אחת לפני שהם מתחייבים, כי לפרק תוכנית תשלומים קשה בהרבה מלארגן נסיעת צפייה."
    },
    money: {
      en: "This is the part that decides whether a Harare purchase happens at all. Remitting capital out of Zimbabwe requires Reserve Bank approval under exchange control, so it is not a routine transfer and should not be planned as one. In practice most purchases are funded from income already held offshore — foreign currency or nostro accounts — rather than converted and sent at the point of sale. Before you commit to anything with fixed dates attached, take the route and the amount to your bank's exchange-control desk and get an answer, because a payment plan assumes you can move money on a schedule and a missed developer instalment is expensive. Expect the UAE side to require documented source of funds before completion: audited company accounts, dividend records, or contracts from a previously sold asset. We will not advise on routes around those controls, and a RERA-registered brokerage has to run KYC on you in any case.",
      fr: "C'est ce point qui détermine si un achat depuis Harare aboutit. Sortir des capitaux du Zimbabwe requiert l'accord de la Banque de réserve au titre du contrôle des changes : ce n'est pas un virement de routine et il ne faut pas le planifier comme tel. En pratique, la plupart des acquisitions sont financées par des revenus déjà détenus à l'étranger — comptes en devises ou nostro — plutôt que convertis et envoyés au moment de la vente. Avant de vous engager sur quoi que ce soit comportant des dates fixes, soumettez le circuit et le montant au service contrôle des changes de votre banque et obtenez une réponse, car un échéancier suppose que vous puissiez transférer selon un calendrier et qu'un défaut sur une échéance promoteur coûte cher. Attendez-vous à ce que le côté émirien exige une origine des fonds documentée avant la finalisation : comptes de société audités, justificatifs de dividendes, ou actes d'un actif précédemment vendu. Nous ne conseillons pas de contournement de ces contrôles, et une agence enregistrée à la RERA doit de toute façon mener son KYC sur vous.",
      ru: "Именно это определяет, состоится ли покупка из Хараре вообще. Вывод капитала из Зимбабве требует одобрения Резервного банка в рамках валютного контроля, поэтому это не рутинный перевод и планировать его так не следует. На практике большинство покупок финансируется из дохода, уже находящегося за рубежом — на валютных или ностро-счетах, — а не конвертируется и отправляется в момент сделки. До того как принять обязательства с фиксированными датами, отнесите маршрут и сумму в отдел валютного контроля вашего банка и получите ответ, потому что рассрочка предполагает возможность переводить деньги по графику, а просрочка платежа застройщику обходится дорого. Ожидайте, что сторона UAE потребует подтверждения происхождения средств до завершения: аудированной отчётности компании, документов о дивидендах или договоров по ранее проданному активу. Мы не консультируем по обходным маршрутам, и брокер с лицензией RERA обязан провести KYC в любом случае.",
      ar: "هذا هو الجزء الذي يحدد ما إذا كان الشراء من هراري سيحدث أصلاً. فتحويل رأس المال إلى خارج زيمبابوي يتطلب موافقة المصرف المركزي بموجب رقابة الصرف، فهو ليس تحويلاً روتينياً ولا ينبغي التخطيط له كذلك. وعملياً تُموَّل معظم المشتريات من دخل محتفظ به خارجياً أصلاً — حسابات بالعملة الأجنبية أو نوسترو — لا عبر التحويل والإرسال عند الشراء. وقبل أن تلتزم بأي شيء له تواريخ محددة، خذ المسار والمبلغ إلى قسم رقابة الصرف في مصرفك واحصل على إجابة، لأن خطة السداد تفترض قدرتك على تحريك الأموال وفق جدول، والتخلّف عن قسط للمطوّر مكلف. وتوقّع أن يطلب الجانب الإماراتي إثبات مصدر الأموال قبل الإتمام: حسابات شركة مدققة، أو سجلات أرباح موزعة، أو عقود لأصل سبق بيعه. ولا نقدّم مشورة بشأن مسارات الالتفاف على تلك الضوابط، وأي وساطة مسجَّلة لدى RERA ملزَمة بإجراء «اعرف عميلك» عليك في كل الأحوال.",
      zh: "这一部分决定了从哈拉雷购房能否成行。根据外汇管制，将资本汇出津巴布韦需要储备银行批准，因此这不是常规转账，也不应按常规规划。实务上，多数购房资金来自本已存放在境外的收入——外汇账户或往来账户——而非在成交时兑换汇出。在承诺任何带有固定日期的事项之前，请把路径与金额带到您银行的外汇管制部门并取得明确答复，因为付款计划的前提是您能按时调动资金，而拖欠开发商的一期费用代价高昂。请预期阿联酋方面会在成交前要求提供资金来源证明：经审计的公司账目、股息记录，或此前已售资产的合同。我们不会就规避这些管制的路径提供建议，而持有 RERA 牌照的中介无论如何都必须对您执行 KYC。",
      vi: "Đây là phần quyết định liệu một giao dịch từ Harare có diễn ra hay không. Chuyển vốn ra khỏi Zimbabwe cần Ngân hàng Dự trữ phê duyệt theo chế độ kiểm soát ngoại hối, nên đó không phải giao dịch thông thường và không nên lập kế hoạch như vậy. Trên thực tế, phần lớn giao dịch được tài trợ từ thu nhập đã có ở nước ngoài — tài khoản ngoại tệ hoặc nostro — chứ không quy đổi và gửi đi tại thời điểm mua. Trước khi cam kết bất cứ điều gì có ngày cố định, hãy mang lộ trình và số tiền đến bộ phận kiểm soát ngoại hối của ngân hàng bạn và lấy câu trả lời, vì kế hoạch thanh toán mặc định rằng bạn có thể chuyển tiền theo lịch, và trễ một kỳ với chủ đầu tư thì rất tốn kém. Hãy chuẩn bị việc phía UAE yêu cầu chứng minh nguồn tiền trước khi hoàn tất: báo cáo công ty đã kiểm toán, hồ sơ cổ tức, hoặc hợp đồng của một tài sản đã bán trước đó. Chúng tôi không tư vấn các lối lách những quy định đó, và sàn có giấy phép RERA dù sao cũng phải thực hiện KYC với bạn.",
      he: "זה החלק שמכריע אם רכישה מהרארה תקרה בכלל. הוצאת הון מזימבבואה מחייבת אישור הבנק המרכזי במסגרת הפיקוח על מטבע חוץ, ולכן זו אינה העברה שגרתית ואין לתכנן אותה ככזו. בפועל, רוב הרכישות ממומנות מהכנסה המוחזקת כבר בחו\"ל — חשבונות מט\"ח או נוסטרו — ולא מהמרה ושליחה במועד העסקה. לפני שאתם מתחייבים למשהו עם תאריכים קבועים, קחו את המסלול ואת הסכום למחלקת הפיקוח על מטבע חוץ בבנק שלכם וקבלו תשובה, כי תוכנית תשלומים מניחה שתוכלו להעביר כספים לפי לוח זמנים, ופיגור בתשלום ליזם יקר. צפו שהצד האמירתי ידרוש הוכחת מקור כספים לפני ההשלמה: דוחות חברה מבוקרים, רישומי דיבידנד, או חוזים של נכס שנמכר קודם. איננו מייעצים על מסלולים לעקיפת הבקרות הללו, ותיווך רשום ב-RERA חייב לבצע עליכם KYC בכל מקרה."
    },
    managing: {
      en: "Once the property exists, running it from Harare is straightforward and largely hands-off. A managed let puts tenant sourcing, Ejari tenancy registration, rent collection and the annual service-charge invoice with the agent, who remits net rent to the account you nominate — which for most Zimbabwean owners is an offshore or foreign currency account rather than one in Harare, keeping the income in the currency it was earned in. Rent is increasingly collected monthly rather than in one or two cheques. The costs to model are the service charge, set per square foot by the building, and a municipality housing fee on rented homes; there is no annual property tax and no UAE tax on the rent itself. Model a vacancy allowance: gross yields of roughly 5-8% assume the unit is occupied.",
      fr: "Une fois le bien livré, le gérer depuis Harare est simple et largement délégable. Une location gérée confie à l'agent la recherche de locataire, l'enregistrement Ejari, l'encaissement des loyers et la facture annuelle de charges, puis le reversement du loyer net sur le compte que vous désignez — pour la plupart des propriétaires zimbabwéens, un compte offshore ou en devises plutôt qu'un compte à Harare, ce qui maintient les revenus dans la monnaie où ils ont été générés. Le loyer est de plus en plus encaissé mensuellement plutôt qu'en un ou deux chèques. Les coûts à modéliser sont les charges, fixées au pied carré par l'immeuble, et une redevance municipale de logement sur les biens loués ; il n'y a pas de taxe foncière annuelle ni d'impôt émirien sur le loyer lui-même. Prévoyez une provision pour vacance : des rendements bruts de 5-8% supposent le bien occupé.",
      ru: "Когда объект существует, управлять им из Хараре просто и почти без участия. Управляемая аренда передаёт агенту поиск арендатора, регистрацию Ejari, сбор аренды и годовой счёт за сервисные сборы; чистую аренду он переводит на указанный вами счёт — для большинства зимбабвийских собственников это зарубежный или валютный счёт, а не счёт в Хараре, что сохраняет доход в валюте, в которой он получен. Аренда всё чаще собирается ежемесячно, а не одним-двумя чеками. Расходы для модели: сервисный сбор, устанавливаемый зданием за квадратный фут, и муниципальный жилищный сбор на сдаваемое жильё; ежегодного налога на недвижимость нет, и UAE не облагает саму аренду. Заложите резерв на простой: валовая доходность примерно 5-8% предполагает, что объект занят.",
      ar: "بمجرد وجود العقار، تصبح إدارته من هراري مباشرة وتكاد لا تتطلب تدخلاً. فالتأجير المُدار يضع إيجاد المستأجر وتسجيل Ejari وتحصيل الإيجار وفاتورة رسوم الخدمات السنوية لدى الوكيل، الذي يحوّل صافي الإيجار إلى الحساب الذي تحدده — وهو لدى معظم المُلّاك الزيمبابويين حساب خارجي أو بالعملة الأجنبية لا حساب في هراري، ما يُبقي الدخل بالعملة التي تحقّق بها. ويُحصَّل الإيجار بصورة متزايدة شهرياً بدل شيك أو شيكين. والتكاليف التي ينبغي احتسابها هي رسوم الخدمات، التي يحددها المبنى للقدم المربعة، ورسم إسكان بلدي على المساكن المؤجَّرة؛ ولا توجد ضريبة عقارية سنوية ولا ضريبة إماراتية على الإيجار نفسه. واحسب مخصصاً للشغور: فالعوائد الإجمالية البالغة نحو 5-8% تفترض أن الوحدة مشغولة.",
      zh: "房产落成之后，从哈拉雷进行管理既简单又基本无需操心。托管出租把寻找租客、Ejari 租约登记、收租与年度物业费账单都交给中介，中介再把净租金汇入您指定的账户——对多数津巴布韦业主而言，这是境外或外汇账户而非哈拉雷的账户，从而让收入保留在其赚取时所用的货币中。租金越来越多按月收取，而非一两张支票。需要测算的成本是物业费（由楼盘按每平方英尺设定）以及出租房屋的市政住房费；没有年度房产税，阿联酋也不对租金本身征税。请纳入空置准备：约 5-8% 的毛回报率以房屋已出租为前提。",
      vi: "Khi bất động sản đã hình thành, việc vận hành từ Harare khá đơn giản và phần lớn không cần bạn nhúng tay. Cho thuê có quản lý giao việc tìm khách thuê, đăng ký Ejari, thu tiền thuê và hóa đơn phí dịch vụ hằng năm cho đại lý, bên này chuyển tiền thuê ròng vào tài khoản bạn chỉ định — với hầu hết chủ sở hữu Zimbabwe, đó là tài khoản ở nước ngoài hoặc tài khoản ngoại tệ chứ không phải tài khoản ở Harare, giữ thu nhập đúng đồng tiền đã kiếm được. Tiền thuê ngày càng được thu theo tháng thay vì một hai tờ séc. Các chi phí cần tính là phí dịch vụ, do tòa nhà ấn định theo foot vuông, và phí nhà ở của thành phố với nhà cho thuê; không có thuế bất động sản hằng năm và UAE không đánh thuế lên chính tiền thuê. Hãy tính cả khoản trống nhà: lợi suất gộp khoảng 5-8% giả định căn hộ có người ở.",
      he: "ברגע שהנכס קיים, ניהולו מהרארה פשוט וכמעט אינו דורש מעורבות. השכרה מנוהלת מעבירה לסוכן את איתור השוכר, רישום ה-Ejari, גביית שכר הדירה וחשבונית דמי הניהול השנתית, והוא מעביר את שכר הדירה נטו לחשבון שתנקבו — שאצל רוב הבעלים הזימבבואים הוא חשבון בחו\"ל או מט\"ח ולא חשבון בהרארה, וכך ההכנסה נשארת במטבע שבו הופקה. שכר הדירה נגבה יותר ויותר חודשית ולא בשיק אחד או שניים. העלויות לתמחור הן דמי הניהול, שנקבעים לפי רגל רבועה על ידי הבניין, ואגרת דיור עירונית על דירות מושכרות; אין מס רכוש שנתי ואין מס אמירתי על שכר הדירה עצמו. תקצבו רזרבה לתקופות ריקות: תשואות ברוטו של כ-5-8% מניחות שהיחידה מאוכלסת."
    },
    areas: ["Jumeirah Village Circle", "Business Bay", "Dubai Marina", "Downtown Dubai", "Dubai Hills Estate"],
  },
];

export function findSourceCity(slug: string): SourceCity | undefined {
  return SOURCE_CITIES.find((c) => c.slug === slug);
}
